### ISSUE TITLE
Disable Sanity Swap - No download of orders

### ISSUE THREAD

**Issue by offerm** [ExchangeUnion/xud#947] opened 2019-05-07 11:54 UTC
When you disable the sanity swap, peer orders will not download to the node.

EDIT:  this issue finally is an enhancement of #970, adding broadcasting orders, even though sanity swaps fail. Ergo when one of the two trading partners disables sanity swaps, it will still receive orders from trading partner.

**Comment by kilrau** [comment] 2019-05-07 12:06
This indeed should work when disabled via `nosanitychecks = true` in `xud.conf`

**Comment by sangaman** [comment] 2019-05-15 03:01
@offerm Are sanity swaps disabled on both sides? If the remote side attempts a sanity swap and fails, they won't send us any orders for that pair even if we've disabled sanity swaps locally.

**Comment by sangaman** [comment] 2019-05-21 12:56
Can we close this issue? Peers who have sanity swaps enabled won't send us orders if the sanity swaps fail, that is by design and the only explanation I have for this. The workaround would be to disable sanity checks on both sides.

**Comment by kilrau** [comment] 2019-05-21 15:02
@offerm

**Comment by kilrau** [comment] 2019-05-23 16:14
In light of [relaxing sanity check](https://github.com/ExchangeUnion/xud/issues/970, @offerm is right, I should receive orders no matter what. So this issue finally is an enhancement of https://github.com/ExchangeUnion/xud/issues/970, adding broadcasting orders, even though sanity swaps fail.

**Comment by sangaman** [comment] 2019-05-24 03:35
I don't think it should be up to the local node to decide whether the remote node should send its orders. In other words, if I only want to share orders with peers that I know I can swap with, I should be able to do that. 

Furthermore, currently nodes aren't aware whether their peers are enforcing sanity swaps or not.

If we still want to change this, it'll require changes to the existing logic. I wouldn't exactly call it a bug.

**Comment by kilrau** [comment] 2019-05-27 10:33
> I don't think it should be up to the local node to decide whether the remote node should send its orders.

Of course! My node always decides what to do and whom to send orders to. We are talking about default behavior. Since we are currently [relaxing sanity checks](https://github.com/ExchangeUnion/xud/issues/970) to make them non-blocking because we are aware of [several issues](https://github.com/ExchangeUnion/xud/issues/988), I believe the default behavior should be to send out orders even though sanity swaps are failing.

https://github.com/ExchangeUnion/xud/issues/971 will make them blocking again once we can rely on sanity swaps to work as expected.

**Comment by sangaman** [comment] 2019-05-28 15:34
Alright I think this makes sense do on a temporary basis as part of making sanity swaps informational-only on a temporary basis until they are reenabled as part of #971.

**Comment by kilrau** [comment] 2019-05-28 17:14
moved to `post-1.0.0` as agreed on the call

**Comment by offerm** [comment] 2019-05-29 05:35
This is not a blocker any more. Order downloads looks good now when I disabled sanitychecks on both sides.

**Comment by erkarl** [comment] 2019-05-29 09:57
I believe this was done/fixed in: https://github.com/ExchangeUnion/xud/pull/992

**Comment by kilrau** [comment] 2019-05-29 11:18
>  this issue finally is an enhancement of #970, adding broadcasting orders, even though sanity swaps fail

Added this to the issue description too. It's moved to `post-1.0.0` and we'll see if we still want that once sanity swaps are fixed up and are "reflecting the truth".

#992 fixed order exchange when sanity swaps are disabled on both peers.

**Comment by erkarl** [comment] 2019-05-29 11:35
Oh, sorry for the confusion.

**Comment by sangaman** [comment] 2019-06-25 13:56
I'm closing this based on discussions from the past few weeks. Rather than rework how sanity swaps work regarding broadcasting orders, we're relaxing them by disabling them by default. Later we'll revisit sanity swaps and ensure they do not give us errors when swaps are possible, then re-enable.

**Closed by sangaman** 2019-06-25 13:56 UTC
Labels: swaps
