### ISSUE TITLE
SendPaymentFailure error for ETH/BTC swap

### ISSUE THREAD

**Issue by raladev** [ExchangeUnion/xud#1585] opened 2020-05-27 11:05 UTC
got SendPaymentFailure for ETH/BTC pair, but swaps work in most cases.

**Steps(from maker side):**
1.sell 300 XUC/DAI 2 1 -> success
2.buy 300 XUC/USDT mkt (taker placed order, maker fills) -> success
3.buy 1 ETH/BTC 0.1 1 -> SendPaymentFailure
4. sell 1 ETH/BTC 0.1 1 -> success
5. buy 1 ETH/BTC 0.1 1 -> success
6. buy 100 XUC/BTC 0.01 1 -> success

**Notes:**
1.Logs of maker's connext node contain 'invalid response - 0' err;
2. In my opinion connext node writes to much in log file (217 msgs per sec).

**Logs:**
[invalid_btc_taker.log](https://github.com/ExchangeUnion/xud-docker/files/4688209/invalid_btc_taker.log)
[invalid_connext_taker.log](https://github.com/ExchangeUnion/xud-docker/files/4688210/invalid_connext_taker.log)
[invalid_xud_taker.log](https://github.com/ExchangeUnion/xud-docker/files/4688211/invalid_xud_taker.log)

[invalid_btc_maker.log](https://github.com/ExchangeUnion/xud-docker/files/4688228/invalid_btc_maker.log)
[invalid_connext_maker.log](https://github.com/ExchangeUnion/xud-docker/files/4688229/invalid_connext_maker.log)
[invalid_xud_maker.log](https://github.com/ExchangeUnion/xud-docker/files/4688230/invalid_xud_maker.log)

**Comment by raladev** [comment] 2020-05-27 11:07
Karl's comments:
- yep, so looks like one of the conditional transfers failed because the receiver side didn't install in 10 seconds, node logs:
```
2020-05-27T10:30:20.402Z [CF-Uninstall] Caught error in node controller: IO_SEND_AND_WAIT timed out after 10s waiting for counterparty reply in uninstall
2020-05-27T10:30:20.403Z [LockService] Releasing lock for 0xe37Af50F3b2cB212049Fc0Ad88dED07b295fd684 after 10253 ms
2020-05-27T10:30:20.405Z [LockService] Done releasing lock for 0xe37Af50F3b2cB212049Fc0Ad88dED07b295fd684
2020-05-27T10:30:20.407Z [CF-Uninstall] Released lock in 10244 ms
2020-05-27T10:30:20.408Z [AppRegistryService] App install failed: Error: IO_SEND_AND_WAIT timed out after 10s waiting for counterparty reply in uninstall
    at /root/modules/cf-core/src/cfCore.ts:222:17
    at ProtocolRunner.runProtocol (/root/modules/cf-core/src/machine/protocol-runner.ts:141:27)
    at ProtocolRunner.initiateProtocol (/root/modules/cf-core/src/machine/protocol-runner.ts:77:27)
    at uninstallAppInstanceFromChannel (/root/modules/cf-core/src/methods/app-instance/uninstall.ts:118:39)
    at UninstallController.executeMethodImplementation (/root/modules/cf-core/src/methods/app-instance/uninstall.ts:77:28)
    at UninstallController.executeMethod (/root/modules/cf-core/src/methods/controller.ts:53:16)
    at RpcRouter.dispatch (/root/modules/cf-core/src/rpc-router.ts:29:17)
```
- so on the receiver side I can't see that App hash 0x590cbd6d74102cc40d4cc3147ec00fbba0930193dbe0aa0a7c8c13b6c2129d88

**Comment by ArjunBhuptani** [comment] 2020-05-27 11:24
Moving my comments in here for longevity --

> In my opinion connext node writes to much in log file (217 msgs per sec).
Looks like `client.getFreeBalance` is being called hundreds of times per second within xud for some reason?

> Logs of maker's connext node contain 'invalid response - 0' err;
This happens when the connext client loses connection to the node. There's a decent to high chance that this is being caused by the above.

> reject install error
The node will reject an install if either the params provided by the sender are incorrect, or if the receiver is unresponsive. In this case, the app identity hash will not make it to the receivers side because the process fails (cleanly) entirely in the sender's channel.

Looks like in this case, the receiver didn't reply to a message from the node? It's definitely weird that the error is being thrown from uninstall, however.

**Comment by kilrau** [comment] 2020-07-07 14:37
Didn't see this anymore after upgrade to connext 7.0.0. Closing.

**Closed by kilrau** 2020-07-07 14:37 UTC
Labels: P2, bug, connext
