### ISSUE TITLE
xud stuck with lnd "error": "12 UNIMPLEMENTED: unknown service lnrpc.Lightning" state

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#1140] opened 2019-08-09 09:17 UTC
### Background

We saw a similar behaviour before in https://github.com/ExchangeUnion/xud/issues/1039 (PR: https://github.com/ExchangeUnion/xud/pull/1045). And https://github.com/ExchangeUnion/xud/issues/1090.

Issue: `xud` doesn't reconnect to lnd when it's restarted and `getinfo` shows `"error": "12 UNIMPLEMENTED: unknown service lnrpc.Lightning"`

### Your environment

* version of `xud`: latest master `1.0.0-testnet.1`
* which operating system (`uname -a` on *Nix): ubuntu 18.04.3
* version of `btcd`, `bitcoind`, `ltcd`, `litecoind`, `geth`, `parity`, `raiden`, `lnd` or other chain backend: docker simnet
* any other relevant environment details: docker simnet

### Steps to reproduce

* simnet up. `getinfo`:
```
    [
      "BTC",
      {
        "error": "",
        "channels": {
          "active": 0,
          "inactive": 0,
          "pending": 0
        },
        "chainsList": [
          {
            "chain": "bitcoin",
            "network": "simnet"
          }
        ],
        "blockheight": 53265,
        "urisList": [],
        "version": "0.6.1-beta commit=v0.6.1-beta",
        "alias": "lndbtc"
      }
    ],
```
* `restart lndbtc`
```
    [
      "BTC",
      {
        "error": "12 UNIMPLEMENTED: unknown service lnrpc.Lightning",
        "chainsList": [],
        "blockheight": 0,
        "urisList": [],
        "version": "",
        "alias": ""
      }
    ],
```
but lndbtc is definitely up and well:
```
simnet > lndbtc-lncli getinfo
{
	"version": "0.6.1-beta commit=v0.6.1-beta",
	"identity_pubkey": "02a61d40bde385fca08520404bcb33999078d4818ccfed3f4f9ebc6f851bd60338",
	"alias": "lndbtc",
	"num_pending_channels": 0,
	"num_active_channels": 0,
	"num_inactive_channels": 0,
	"num_peers": 0,
	"block_height": 53294,
	"block_hash": "1f4602cc9528966854fbc754c921e6b8132ff2f006fe640c9f7e9476cc6e3861",
	"best_header_timestamp": 1565342047,
	"synced_to_chain": true,
	"testnet": false,
	"chains": [
		{
			"chain": "bitcoin",
			"network": "simnet"
		}
	],
	"uris": null
}
```
[xud.log](https://github.com/ExchangeUnion/xud/files/3485605/xud.log)
[lnd.log](https://github.com/ExchangeUnion/xud/files/3485618/lnd.log)

### Expected behaviour

xud successfully reconnect to lnd after restart

### Actual behaviour

xud fails to reconnect to lnd after restart with `"error": "12 UNIMPLEMENTED: unknown service lnrpc.Lightning"`

**Comment by kilrau** [comment] 2019-08-09 09:23
As before, restarting `xud` fixes it:

```
simnet > restart xud
Restarting simnet_xud_1 ... done
simnet > getinfo
D0809 09:23:22.089956252      57 env_linux.cc:71]            Warning: insecure environment read function 'getenv' used
{
  "version": "1.0.0-testnet.1",
  "nodePubKey": "0309bfdaa83dc3099c43f3abe2059afe25ae8ab12f364b9a171783b41a670f4d59",
  "urisList": [
    "0309bfdaa83dc3099c43f3abe2059afe25ae8ab12f364b9a171783b41a670f4d59@0.0.0.0:8885"
  ],
  "numPeers": 3,
  "numPairs": 1,
  "orders": {
    "peer": 20,
    "own": 0
  },
  "lndMap": [
    [
      "BTC",
      {
        "error": "",
        "channels": {
          "active": 0,
          "inactive": 0,
          "pending": 0
        },
        "chainsList": [
          {
            "chain": "bitcoin",
            "network": "simnet"
          }
        ],
        "blockheight": 53302,
        "urisList": [],
        "version": "0.6.1-beta commit=v0.6.1-beta",
        "alias": "lndbtc"
      }
    ],
```

**Comment by erkarl** [comment] 2019-08-09 10:41
Can you reproduce the issue and see if lnd is unlocked when xud returns such output. I have a feeling it's related to the unlock logic not working reliably. I made it more reliable in the docker tor PR.

**Comment by sangaman** [comment] 2019-08-09 12:51
Does lnd start up requiring a password to unlock it? If so, it's most likely the same root cause as what's in #1090, but this reminds me to open an issue with the grpc team to see if there's a bug or hidden solution since I've exhausted all options I could think of.

**Comment by kilrau** [comment] 2019-08-09 14:38
You are right, lnd is locked when xud get's stuck on `"error": "12 UNIMPLEMENTED: unknown service lnrpc.Lightning"`. So please open this issue [as we discussed before](https://github.com/ExchangeUnion/xud/issues/1090#issuecomment-514279119) @sangaman

**Comment by sangaman** [comment] 2019-08-09 15:24
Closing this as a duplicate of #1090.

**Closed by sangaman** 2019-08-09 15:24 UTC
Labels: bug, duplicate
