### ISSUE TITLE
Order stuck on-hold (arby exits with `Unrecoverable error`)

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#1835] opened 2020-08-02 15:55 UTC
```
020-08-02 11:43:58.5858 [OpenDEX] info: All OpenDEX orders have been removed
2020-08-02 11:43:59.5959 [Centralized] info: All CEX orders have been removed
2020-08-02 11:44:04.044 [Centralized] warn: Price feed lost. Retrying in 5000ms.
2020-08-02 11:44:04.044 [Centralized] trace: ETHBTC stream closed
2020-08-02 11:44:04.044 [OpenDEX] info: All OpenDEX orders have been removed
2020-08-02 11:44:04.044 [Centralized] info: All CEX orders have been removed
2020-08-02 11:44:09.099 [OpenDEX] trace: Base asset balance 0.13336819 (maxinbound: 90071992.54740991, maxoutbound: 0.13336819) and quote asset balance 0.01070385 (maxinbound: 0.00337293, maxoutbound: 0.01055893).
2020-08-02 11:44:09.099 [GLOBAL] info: Unrecoverable error. Cleaning up
2020-08-02 11:44:09.099 [Centralized] trace: ETHBTC stream closed
2020-08-02 11:44:09.099 [Centralized] warn: Failed to remove orders: binance GET https://api.binance.com/api/v3/openOrders?timestamp=1596368649941&recvWindow=5000&symbol=ETHBTC&signature=ef469f8cb63492195219968bfd8943830ded5a695710c78e697996fc927fa114 system request to https://api.binance.com/api/v3/openOrders?timestamp=1596368649941&recvWindow=5000&symbol=ETHBTC&signature=ef469f8cb63492195219968bfd8943830ded5a695710c78e697996fc927fa114 failed, reason: read ECONNRESET - retrying in 1000ms
2020-08-02 11:44:09.099 [OpenDEX] info: All OpenDEX orders have been removed
2020-08-02 11:44:11.1111 [Centralized] info: All CEX orders have been removed
Shutdown complete. Goodbye, Arby.
2020-08-02 11:44:44,460 INFO exited: arby (exit status 0; expected)
```

Full logs from 35 mins before crash: https://paste.ubuntu.com/p/kx6vbVDwPD/

**Comment by kilrau** [comment] 2020-08-25 11:41
And one more case leading to this. Arby logs:
```
2020-08-25 11:39:22.2222 [Centralized] info: Base asset balance 123 and quote asset balance 321
2020-08-25 11:39:22.2222 [OpenDEX] trace: Base asset balance 2.79963 (maxinbound: 90071992.54740991, maxoutbound: 2.79963) and quote asset balance 0.1 (maxinbound: 0.03199818, maxoutbound: 0.09866667).
2020-08-25 11:39:23.2323 [Centralized] trace: ETHBTC established connection to wss://stream.binance.com:9443/ws/ethbtc@aggTrade
2020-08-25 11:39:23.2323 [Centralized] trace: heartbeat from ETHBTC socket
2020-08-25 11:39:24.2424 [Centralized] trace: New price: 0.034059
2020-08-25 11:39:24.2424 [OpenDEX] trace: Starting to update OpenDEX orders
2020-08-25 11:39:24.2424 [OpenDEX] trace: Replacing ETH/BTC buy order with id arby-ETH/BTC-buy-order, quantity 2.98652974 and price 0.03303723
2020-08-25 11:39:24.2424 [OpenDEX] trace: Replacing ETH/BTC sell order with id arby-ETH/BTC-sell-order, quantity 0.91212878 and price 0.03508077
2020-08-25 11:39:24.2424 [OpenDEX] trace: Creating ETH/BTC sell order with id arby-ETH/BTC-sell-order, quantity 0.91212878 and price 0.03508077
2020-08-25 11:39:25.2525 [OpenDEX] trace: Creating ETH/BTC buy order with id arby-ETH/BTC-buy-order, quantity 2.98652974 and price 0.03303723
2020-08-25 11:39:25.2525 [Centralized] trace: New price: 0.034052
2020-08-25 11:39:25.2525 [OpenDEX] trace: Order arby-ETH/BTC-sell-order created
2020-08-25 11:39:25.2525 [OpenDEX] trace: Order arby-ETH/BTC-buy-order created
2020-08-25 11:39:25.2525 [OpenDEX] trace: OpenDEX orders updated
2020-08-25 11:39:26.2626 [Centralized] trace: New price: 0.034052
2020-08-25 11:39:28.2828 [Centralized] trace: New price: 0.034056
2020-08-25 11:39:28.2828 [OpenDEX] trace: Starting to update OpenDEX orders
2020-08-25 11:39:28.2828 [OpenDEX] trace: Replacing ETH/BTC buy order with id arby-ETH/BTC-buy-order, quantity 2.98679282 and price 0.03303432
2020-08-25 11:39:28.2828 [OpenDEX] trace: Replacing ETH/BTC sell order with id arby-ETH/BTC-sell-order, quantity 0.91220913 and price 0.03507768
2020-08-25 11:39:28.2828 [OpenDEX] trace: Order arby-ETH/BTC-sell-order created
2020-08-25 11:39:28.2828 [OpenDEX] trace: Order arby-ETH/BTC-buy-order created
2020-08-25 11:39:28.2828 [OpenDEX] trace: OpenDEX orders updated
2020-08-25 11:39:29.2929 [Centralized] trace: New price: 0.034057
2020-08-25 11:39:29.2929 [OpenDEX] trace: Starting to update OpenDEX orders
2020-08-25 11:39:29.2929 [OpenDEX] trace: Replacing ETH/BTC buy order with id arby-ETH/BTC-buy-order, quantity 2.98670512 and price 0.03303529
2020-08-25 11:39:29.2929 [OpenDEX] trace: Replacing ETH/BTC sell order with id arby-ETH/BTC-sell-order, quantity 0.91218234 and price 0.03507871
2020-08-25 11:39:29.2929 [OpenDEX] trace: Order arby-ETH/BTC-sell-order created
2020-08-25 11:39:29.2929 [OpenDEX] trace: Order arby-ETH/BTC-buy-order created
2020-08-25 11:39:29.2929 [OpenDEX] trace: OpenDEX orders updated
2020-08-25 11:39:30.3030 [Centralized] trace: New price: 0.034057
2020-08-25 11:39:30.3030 [Centralized] trace: New price: 0.034057
2020-08-25 11:39:31.3131 [Centralized] trace: New price: 0.034059
2020-08-25 11:39:31.3131 [OpenDEX] trace: Starting to update OpenDEX orders
2020-08-25 11:39:31.3131 [OpenDEX] trace: Replacing ETH/BTC buy order with id arby-ETH/BTC-buy-order, quantity 2.98652974 and price 0.03303723
2020-08-25 11:39:31.3131 [OpenDEX] trace: Replacing ETH/BTC sell order with id arby-ETH/BTC-sell-order, quantity 0.91212878 and price 0.03508077
2020-08-25 11:39:32.3232 [Centralized] trace: New price: 0.03406
2020-08-25 11:39:32.3232 [Centralized] trace: New price: 0.034058
2020-08-25 11:39:32.3232 [OpenDEX] trace: Order arby-ETH/BTC-sell-order created
2020-08-25 11:39:32.3232 [OpenDEX] trace: Order arby-ETH/BTC-buy-order created
2020-08-25 11:39:32.3232 [OpenDEX] trace: OpenDEX orders updated
2020-08-25 11:39:33.3333 [Centralized] trace: heartbeat from ETHBTC socket
2020-08-25 11:39:39.3939 [Centralized] trace: New price: 0.034055
2020-08-25 11:39:39.3939 [OpenDEX] trace: Starting to update OpenDEX orders
2020-08-25 11:39:39.3939 [OpenDEX] trace: Replacing ETH/BTC buy order with id arby-ETH/BTC-buy-order, quantity 2.98688053 and price 0.03303335
2020-08-25 11:39:39.3939 [OpenDEX] trace: Replacing ETH/BTC sell order with id arby-ETH/BTC-sell-order, quantity 0.91223591 and price 0.03507665
2020-08-25 11:39:39.3939 [OpenDEX] trace: Order arby-ETH/BTC-sell-order created
2020-08-25 11:39:39.3939 [OpenDEX] trace: Order arby-ETH/BTC-buy-order created
2020-08-25 11:39:39.3939 [OpenDEX] trace: OpenDEX orders updated
2020-08-25 11:39:42.4242 [Centralized] trace: New price: 0.034054
2020-08-25 11:39:42.4242 [OpenDEX] trace: Starting to update OpenDEX orders
2020-08-25 11:39:42.4242 [OpenDEX] trace: Replacing ETH/BTC buy order with id arby-ETH/BTC-buy-order, quantity 2.98696824 and price 0.03303238
2020-08-25 11:39:42.4242 [OpenDEX] trace: Replacing ETH/BTC sell order with id arby-ETH/BTC-sell-order, quantity 0.9122627 and price 0.03507562
2020-08-25 11:39:42.4242 [OpenDEX] trace: Order arby-ETH/BTC-sell-order created
2020-08-25 11:39:42.4242 [OpenDEX] warn: 9 FAILED_PRECONDITION: BTC outbound balance of 0 is not sufficient for order amount of 9866667. Retrying in 5000ms.
2020-08-25 11:39:47.4747 [Centralized] info: Base asset balance 123 and quote asset balance 321
2020-08-25 11:39:47.4747 [OpenDEX] trace: Base asset balance 2.79963 (maxinbound: 90071992.54740991, maxoutbound: 2.79963) and quote asset balance 0.1 (maxinbound: 0.03199818, maxoutbound: 0.09866667).
2020-08-25 11:39:48.4848 [Centralized] trace: New price: 0.034054
2020-08-25 11:39:48.4848 [OpenDEX] trace: Starting to update OpenDEX orders
2020-08-25 11:39:48.4848 [OpenDEX] trace: Replacing ETH/BTC buy order with id arby-ETH/BTC-buy-order, quantity 2.98696824 and price 0.03303238
2020-08-25 11:39:48.4848 [OpenDEX] trace: Replacing ETH/BTC sell order with id arby-ETH/BTC-sell-order, quantity 0.9122627 and price 0.03507562
2020-08-25 11:39:48.4848 [Centralized] trace: New price: 0.034055
2020-08-25 11:39:48.4848 [OpenDEX] trace: Order arby-ETH/BTC-sell-order created
2020-08-25 11:39:48.4848 [GLOBAL] info: Unrecoverable error. Cleaning up.
2020-08-25 11:39:48.4848 [Centralized] info: Removing CEX orders
2020-08-25 11:39:48.4848 [Centralized] trace: ETHBTC stream closed
2020-08-25 11:39:48.4848 [OpenDEX] info: All OpenDEX orders have been removed
2020-08-25 11:39:49.4949 [Centralized] info: Finished removing CEX orders
Shutdown complete. Goodbye, Arby.
2020-08-25 11:39:50,581 INFO exited: arby (exit status 0; expected)
2020-08-25 11:39:51,586 INFO spawned: 'arby' with pid 86
2020-08-25 11:39:52,589 INFO success: arby entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```

**Comment by raladev** [comment] 2020-08-25 18:41
Got it too:
[arby2_log_stuck.log](https://github.com/ExchangeUnion/xud/files/5125691/arby2_log_stuck.log)
[xud_arby_stuck.log](https://github.com/ExchangeUnion/xud/files/5125694/xud_arby_stuck.log)

**Comment by sangaman** [comment] 2020-08-25 19:08
> Bob trying to remove the stuck arby order:
> 
> ```
> simnet > listorders -j
> {
>   "ordersMap": [
>     [
>       "BTC/USDT",
>       {
>         "buyOrdersList": [],
>         "sellOrdersList": []
>       }
>     ],
>     [
>       "ETH/BTC",
>       {
>         "buyOrdersList": [
>           {
>             "price": 0.03357364,
>             "quantity": 7237045938,
>             "pairId": "ETH/BTC",
>             "id": "0dfb7860-e3a3-11ea-8bd1-2d84ece41194",
>             "nodeIdentifier": {
>               "nodePubKey": "03df4f36fa35bd242263e8d09d6b422108dab1f08d91237bb3aa2dad957cf08a71",
>               "alias": "SheriffSolution"
>             },
>             "localId": "arby-ETH/BTC-buy-order",
>             "createdAt": 1598010004198,
>             "side": 0,
>             "isOwnOrder": true,
>             "hold": 7237045938
>           }
>         ],
>         "sellOrdersList": []
>       }
>     ],
>     [
>       "LTC/BTC",
>       {
>         "buyOrdersList": [],
>         "sellOrdersList": []
>       }
>     ],
>     [
>       "LTC/USDT",
>       {
>         "buyOrdersList": [],
>         "sellOrdersList": []
>       }
>     ]
>   ]
> }
> simnet > removeorder 0dfb7860-e3a3-11ea-8bd1-2d84ece41194
> Error: 5 NOT_FOUND: order with local id 0dfb7860-e3a3-11ea-8bd1-2d84ece41194 does not exist
> ```
> 
> It might be a bug on xud after all. Thoughts? @erkarl @sangaman

Just a note here that attempting to remove the order by the global id won't work, it's expecting the local id (`arby-ETH/BTC-buy-order` in this case).

**Comment by kilrau** [comment] 2020-08-26 09:27
> Just a note here that attempting to remove the order by the global id won't work, it's expecting the local id (`arby-ETH/BTC-buy-order` in this case).

That is clear and was an oversight on my end, but in https://github.com/ExchangeUnion/xud/issues/1835#issuecomment-679894767 below you can see the error it gave me when I used the local id correctly.

**Comment by kilrau** [comment] 2020-09-01 13:06
Just encountered this again with [latest xud master](https://github.com/ExchangeUnion/xud/commit/cfdedaf3c19dab5d95a7583ec3c107689ab851df).
1. I noticed arby errored with `Unrecoverable error` again, just like before.
2. `xud` logs show failure to place order:
```
01/09/2020 12:02:54.478 [RPC] error: call /xudrpc.Xud/PlaceOrderSync errored with code 3: order with local id arby-ETH/BTC-sell-order has a quantity of 10000 on hold
01/09/2020 12:02:54.479 [RPC] error: call /xudrpc.Xud/PlaceOrderSync errored with code 5: order with id arby-ETH/BTC-buy-order could not be found
```
3. and indeed there is an order on hold that shouldn't be:
```
  "ordersMap": [
    [
      "ETH/BTC",
      {
        "buyOrdersList": [],
        "sellOrdersList": [
          {
            "price": 0.0406026,
            "quantity": 10000,
            "pairId": "ETH/BTC",
            "id": "254925e0-ec49-11ea-9ff0-dd2aa9506f54",
            "nodeIdentifier": {
              "nodePubKey": "02799dff47d38da549c9f9e3dcd94388e3a9fe05b4ea50ea0636562b4ba2b4ca4a",
              "alias": "AttitudeErase"
            },
            "localId": "arby-ETH/BTC-sell-order",
            "createdAt": 1598960949054,
            "side": 1,
            "isOwnOrder": true,
            "hold": 10000
          }
        ]
      }
    ],
```

Since I have one machine where this can be reproduced very reliably (testnet), I'll run reproduce this with xud in log level trace once more and attach logs here.

**Comment by sangaman** [comment] 2020-09-02 18:46
I'm closing this again because the issue above was not caused by the original issue here, where replacing orders could leave orders stuck on hold forever, but rather because of a hold caused by a "pending" connext payment due to #1850.

**Closed by sangaman** 2020-09-02 18:46 UTC
Labels: P0, critical bug
