### ISSUE TITLE
developer option: don't remove orders from a peer that I failed to swap with from orderbook

### ISSUE THREAD

**Issue by raladev** [ExchangeUnion/xud#1496] opened 2020-04-22 14:32 UTC
### Background

Order missing from orderbook of taker after failed swap in scheme Alice - simnet-node - Bob

### Your environment

Current  master branch + docker installation with simnet network

### Steps to reproduce

1. Perform first installation of xud-docker-simnet and wait for active channels (Alice)
2.  Perform second installation of xud-docker-simnet and wait for active channels (Bob)
3. Place buy 0.01 LTC/BTC 0.0001 1 order to orderbook as Alice
4. Fill it as Bob (sell  0.01 LTC/BTC 0.0001 1)

### Expected behaviour

Order returns to the orderbook of taker after failed swap

### Actual behaviour

No order in order book after failed swap; No repeating as logs said;
Also, Alice lost connection with one of the peers during the swap, but Bob is not.

### A lot of screens
left - Bob, right - Alice

[Screenshot from 2020-04-22 17-13-39](https://user-images.githubusercontent.com/29906866/79994633-e6429f80-84be-11ea-91a8-7e43c34311be.png)
[Screenshot from 2020-04-22 17-16-22](https://user-images.githubusercontent.com/29906866/79994638-e773cc80-84be-11ea-81d1-26da2d015f0f.png)
[Screenshot from 2020-04-22 17-18-46](https://user-images.githubusercontent.com/29906866/79994640-e80c6300-84be-11ea-8541-690f7336fda3.png)

### Xud logs
[logs_of_taker.log](https://github.com/ExchangeUnion/xud/files/4516769/logs_of_taker.log)
[logs_of_maker.log](https://github.com/ExchangeUnion/xud/files/4516782/logs_of_maker.log)

**Comment by sangaman** [comment] 2020-04-22 18:47
Just so I'm clear, the issue is that Bob's order disappeared after the swap failed? The behavior I'd expect here is for Bob's order to enter both Bob's and ALice's order book as a limit order, and for Alice's order to disappear from Bob's order book while remaining in Alice's order book..

**Comment by raladev** [comment] 2020-04-23 09:14
> Just so I'm clear, the issue is that Bob's order disappeared after the swap failed? The behavior I'd expect here is for Bob's order to enter both Bob's and ALice's order book as a limit order, and for Alice's order to disappear from Bob's order book while remaining in Alice's order book..

issue - Order of Alice disappeared in order book of Bob after failed swap, but still exists in order book of Alice;

1. Alice places limit order buy - order appears in both orderbooks 
2. Bob places limit order sell with the same price and qty - swap starts- order of Alice dissappears from order book of Bob for swap performing (we see removing in logs)
3. Swap fails - Order of Alice should be returned to orderbook of Bob (because Alice still has it); Order of Bob - idk, I think it should be cancelled after unsuccessful swap, but im not sure about behavior of Bobs order. @kilrau

**Comment by kilrau** [comment] 2020-04-23 10:27
>     3\. Swap fails - Order of Alice should be returned to orderbook of Bob (because Alice still has it); Order of Bob - idk, I think it should be cancelled after unsuccessful swap, but im not sure about behavior of Bobs order. @kilrau

How it should be:
After the swap failed, Alice's buy order should return to Alice's AND Bob's order book. Or did we have a rule saying "if an order failed to swap once, we don't want to look at it ever again" so that the described behavior is correct: the order re-appearing in Alice's but **not** in Bob's order book? @sangaman 

That Bob failed order simply disappears is correct (Reason is that in the case of a failed swap attempt we can't have two matching orders sit in the order book at the same time and don't match. Looking at the error message `failed to swap <quantity> <currency> with peer order <order id>` this is not clear though. I think we should add "Your order was discarded." Wdyt? @sangaman

**Comment by kilrau** [comment] 2020-04-23 10:31
[Alice (maker).log](https://github.com/ExchangeUnion/xud/files/4516782/logs_of_maker.log)
[Bob (taker).log](https://github.com/ExchangeUnion/xud/files/4516769/logs_of_taker.log)

Funnily Bob's logs don't show anything about the swap. Might have to do with them loosing p2p connection? Even though accordig to the timestamp that only happened later. Anyhow we should have a close look at this :thinking:

**Comment by sangaman** [comment] 2020-04-23 18:56
> How it should be:
After the swap failed, Alice's buy order should return to Alice's AND Bob's order book. Or did we have a rule saying "if an order failed to swap once, we don't want to look at it ever again" so that the described behavior is correct: the order re-appearing in Alice's but not in Bob's order book?

Yes, this is the intended behavior currently, although since it's not documented this may be a good indication that we need to explain this more clearly.

If we try to take an order and it fails, we get rid of that error. That makes sense to me with the goal of trying to minimize failed swaps (if it fails once, it's likely to fail again), and if we put it back in the order book we're likely to keep trying it since it may stay as the best available order.

> That Bob failed order simply disappears is correct (Reason is that in the case of a failed swap attempt we can't have two matching orders sit in the order book at the same time and don't match. Looking at the error message failed to swap <quantity> <currency> with peer order <order id> this is not clear though. I think we should add "Your order was discarded." Wdyt?

And here actually I'd expect Bob's order to remain, just because he couldn't swap with Alice doesn't mean he wouldn't want to broadcast it to others.

> Funnily Bob's logs don't show anything about the swap. Might have to do with them loosing p2p connection? Even though accordig to the timestamp that only happened later. Anyhow we should have a close look at this thinking

Are these not the relevant lines from the log?

```
22/04/2020 14:12:48.194 [RPC] [34mdebug[39m: received call /xudrpc.Xud/PlaceOrderSync
22/04/2020 14:12:48.195 [ORDERBOOK] [34mdebug[39m: removed order 83fbf4b0-84a1-11ea-8264-214d6af3d835 while matching order 582ab130-84a3-11ea-9eb0-8f7889e2a35c
22/04/2020 14:12:48.196 [ORDERBOOK] [34mdebug[39m: matched with peer 03c3f01c700bdcdc5b1898d48845ca6dd49c33240ed82b106ef2cfc224726e5775 (BossDoor), executing swap on taker 582ab130-84a3-11ea-9eb0-8f7889e2a35c and maker 83fbf4b0-84a1-11ea-8264-214d6af3d835 for 1000000
22/04/2020 14:12:48.214 [LND-LTC] [34mdebug[39m: could not find a route to 02ddba97ced443ec8e16dc87ce66dd9f941add4a22097534add9ef0427ab517502 for 1000000 units with finalCltvDelta 576: undefined
22/04/2020 14:12:48.214 [ORDERBOOK] [31merror[39m: swap between orders 83fbf4b0-84a1-11ea-8264-214d6af3d835 & 582ab130-84a3-11ea-9eb0-8f7889e2a35c failed due to NoRouteFound
22/04/2020 14:12:48.215 [ORDERBOOK] [33mwarn[39m: swap for 1000000 failed during order matching due to NoRouteFound, will repeat matching routine for failed quantity
22/04/2020 14:12:48.215 [ORDERBOOK] [34mdebug[39m: repeating matching routine for 582ab130-84a3-11ea-9eb0-8f7889e2a35c for failed quantity of 1000000
```

I'm going to try to reproduce this myself and see if I can shed some more light on what's going on. This may also be a good simulation test case (swap fails, the now-unmatched order does what we expect).

**Comment by raladev** [comment] 2020-04-24 12:56
---And here actually I'd expect Bob's order to remain, just because he couldn't swap with Alice doesn't mean he wouldn't want to broadcast it to others.

In this case with Alice-simnet1-Bob schema, simnet1 (or just John) will have buy 0.01 LTC/BTC 0.0001  and sell 0.01 LTC/BTC 0.0001  orders in orderbook. This case looks a bit wrong when there are orders in the order book that should have been mailed. 

Also there will be a similar situation (2 orders in John orderbook) if Bob tries to place this order again without Alices order in his orderbook.

**Comment by kilrau** [comment] 2020-04-24 14:13
What we should extract from here in a separate discussion: remove or not to remove an order that failed to swap form the orderbook

**Comment by kilrau** [comment] 2020-04-24 14:54
Other than that: After @sangaman confirmed that all of this behavior is 100% what we'd expect, we can close this.

**Comment by sangaman** [comment] 2020-04-24 15:06
> In this case with Alice-simnet1-Bob schema, simnet1 (or just John) will have buy 0.01 LTC/BTC 0.0001 and sell 0.01 LTC/BTC 0.0001 orders in orderbook. This case looks a bit wrong when there are orders in the order book that should have been mailed.

I realize this is strange but I think it's a reality of having a decentralized order book. If Alice is connected to Bob, and Bob is connected to Carol, but Alice and Carol aren't connected to each other, Bob may hear of matching orders from Alice and Carol that don't get executed because they don't know about one another. Bob could always fill both orders and play the role of middle man/market maker in this case.

> What we should extract from here in a separate discussion: remove or not to remove an order that failed to swap form the orderbook

I put my thoughts above but what it mainly boils down to is whether we can expect a swap that just failed to work a few seconds or minutes later. I would expect that most of the time it won't, and it will require something like new channels to be created, existing channels to be rebalanced, or intermediary nodes that were offline to come online. Removing the failed order from the order book will reduce the likelihood of further failed swaps. What I'd want to avoid is a situation where we get stuck retrying the same unswappable order over and over.

**Comment by raladev** [comment] 2020-04-24 16:41
--Removing the failed order from the order book will reduce the likelihood of further failed swaps. What I'd want to avoid is a situation where we get stuck retrying the same unswappable order over and over.
Then, in this case we should delete all orders of certain peer in certain orderbook. Because swapping with second order of the peer will be unsuccessful too.

And question:
Should we add failed Bobs order to order book of Alice? Or should we add it only to Johns and Bobs orderbooks?

**Comment by kilrau** [comment] 2020-05-01 18:55
@sangaman let's do a config option to **not** remove orders from a peer where a swap once failed. Debugging is unbelievably cumbersome with the current behavior.

**Closed** 2020-05-07 09:25 UTC
Labels: P2
