### ISSUE TITLE
Propagate new seed currencies & pairs on existing db

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#1917] opened 2020-09-24 13:37 UTC
As a follow-up of https://github.com/ExchangeUnion/xud/pull/1907 we want to apply this behaviour to `currencies` & `pairs` in `seeds` too: [add new ones, don't touch existing ones](https://github.com/ExchangeUnion/xud/issues/1645#issuecomment-694735517)

**Comment by kilrau** [comment] 2020-09-29 15:44
This caused USDT to disappear on my simnet environment (which had USDT, but did **not** have DAI before) getting me into the weird situations where I have pairs for USDT, but don't have USDT as currency:
```
simnet > getbalance

Balance:
┌──────────┬───────────────┬────────────────────────────┬───────────────────────────────┐
│ Currency │ Total Balance │ Channel Balance (Tradable) │ Wallet Balance (Not Tradable) │
├──────────┼───────────────┼────────────────────────────┼───────────────────────────────┤
│ BTC      │ 1000.78146242 │ 2.86976312                 │ 997.9116993                   │
├──────────┼───────────────┼────────────────────────────┼───────────────────────────────┤
│ DAI      │ 0             │ 0                          │ 0                             │
├──────────┼───────────────┼────────────────────────────┼───────────────────────────────┤
│ ETH      │ 22.109928     │ 7.109928                   │ 15                            │
├──────────┼───────────────┼────────────────────────────┼───────────────────────────────┤
│ LTC      │ 1013.88977649 │ 8.88999599                 │ 1004.9997805                  │
└──────────┴───────────────┴────────────────────────────┴───────────────────────────────┘
simnet > listpairs
Trading Pairs:
┌──────────────┐
│ Trading pair │
├──────────────┤
│ ETH / BTC    │
├──────────────┤
│ LTC / BTC    │
├──────────────┤
│ BTC / USDT   │
├──────────────┤
│ LTC / USDT   │
├──────────────┤
│ USDT / DAI   │
└──────────────┘
```

**Comment by rsercano** [comment] 2020-09-29 16:12
Closing this one since the issue is related with token address @kilrau and if you want we can raise another one over changed/deleted topic @kilrau

**Closed by rsercano** 2020-09-29 16:12 UTC
Labels: P1
