### ISSUE TITLE
Getbalance Slow

### ISSUE THREAD

**Issue by offerm** [ExchangeUnion/xud#1329] opened 2019-11-11 05:43 UTC
1. takes long time on xud1/simnet. Not sure why

2. I need a way to know how much I can trade. for this I need the max out going and incoming channel for each asset. The current information can't help with this. Incoming is not provided at all and out going (channel balance ) my be over multiple channels so it can't be used in a single swap. 

not very urgent

**Comment by sangaman** [comment] 2019-11-11 06:04
For #2, to be clear, you'd want to see the highest balance available on a single channel? I'm not sure how useful that would be in real-world scenarios given that these maximums may only apply to trades with a single peer - or no peer in some cases. But we can still return it and display it in the cli though, maybe with some caveat that it is only a theoretical maximum.

The total inbound capacity may be a worthwhile stat to display as well.

For #1, how often are you seeing this and how long are the wait times? The `getbalance` call was recently changed to loop through all channels and calculate a more detailed breakdown than what lnd returns in its `channelbalance` call, so that might be related. It might make sense to track #2, which is an enhancement, in a separate issue from this.

**Comment by offerm** [comment] 2019-11-12 06:45
#1 - situation is permanent on xud1
```
xud@xud1-simnet-exchangeunion-com:~$ time xucli getbalance
Balance:
┌──────────┬──────────────────┬────────────────────────────┬───────────────────────────────┐
│ Currency │ Total Balance    │ Channel Balance (Tradable) │ Wallet Balance (Not Tradable) │
├──────────┼──────────────────┼────────────────────────────┼───────────────────────────────┤
│ BTC      │ 2912356.63689038 │ 17.98936088                │ 2912338.6475295               │
├──────────┼──────────────────┼────────────────────────────┼───────────────────────────────┤
│ DAI      │ 148458.31743999  │ 148458.31743999            │ 0                             │
├──────────┼──────────────────┼────────────────────────────┼───────────────────────────────┤
│ LTC      │ 2600205.16148773 │ 2134.34773565              │ 2598070.81375208              │
├──────────┼──────────────────┼────────────────────────────┼───────────────────────────────┤
│ WETH     │ 499.8            │ 499.8                      │ 0                             │
└──────────┴──────────────────┴────────────────────────────┴───────────────────────────────┘
real    0m10.550s
user    0m0.240s
sys     0m0.024s
```

#2 - what I need is a reliable way to ensure that an order I'm about to issue can be placed. 
So, if I'm about to place a `buy 1 BTC/DIA 8800`  order, I need to know that I can send 8800 DAI and can receive 1 BTC. Ideally it should take into account my other orders of that pair in that direction. 
For example, if I already sent `buy 1 BTC/DIA 8800`  and I'm now sending `buy 2 BTC/DAI 8600' I want to ensure that I can send 2*8600+1*8800 and receive 3 BTC.

**Comment by kilrau** [comment] 2019-11-12 12:27
This issue is about #1 only. #2 moved to https://github.com/ExchangeUnion/xud/issues/1331.

**Comment by engwarrior** [comment] 2020-02-09 08:47
Pls provide estimate for this task.

**Comment by kilrau** [comment] 2020-02-10 13:11
I think this one is hard reproduce for you @engwarrior since we are only seeing this behavior on one of our simnet instances.

**Comment by kilrau** [comment] 2020-04-22 15:24
We haven't seen this in a long while. Closing.

**Closed by kilrau** 2020-04-22 15:24 UTC
Labels: P2, bug
