### ISSUE TITLE
Reconnection issues

### ISSUE THREAD

**Issue by erkarl** [ExchangeUnion/xud#1284] opened 2019-10-10 10:16 UTC
I experienced the following scenario between node1 and node2 after which node2 was no longer connected to node1. Looks like node2 stopped reconnection attempts because it thought it was already connected, but in reality it was not.

Any thoughts what could have caused this @sangaman?
 
# node1
```
xud_1        | 09/10/2019 20:34:31.503 [P2P] info: Peer 02ca8c5cdccf1fb10bcc5813517fa2d132492f35b206698b008c5c75c9671e80c1 socket closed
xud_1        | 09/10/2019 20:34:40.365 [P2P] error: Peer (02ca8c5cdccf1fb10bcc5813517fa2d132492f35b206698b008c5c75c9671e80c1): error: response timeout (302be460-ead4-11e9-aab4-a1791a834396) 
xud_1        | 09/10/2019 20:34:40.365 [P2P] debug: Peer (02ca8c5cdccf1fb10bcc5813517fa2d132492f35b206698b008c5c75c9671e80c1): closing socket. reason: ResponseStalling
xud_1        | 09/10/2019 20:34:40.366 [ORDERBOOK] debug: removed all orders for peer 02ca8c5cdccf1fb10bcc5813517fa2d132492f35b206698b008c5c75c9671e80c1
xud_1        | 09/10/2019 20:34:40.366 [P2P] info: Peer 02ca8c5cdccf1fb10bcc5813517fa2d132492f35b206698b008c5c75c9671e80c1 socket closed
```
 
# node2
```
xud_1        | 09/10/2019 20:34:13.166 [P2P] info: Peer 02529a91d073dda641565ef7affccf035905f3d8c88191bdea83a35f37ccce5d64 socket closed
xud_1        | 09/10/2019 20:34:13.168 [ORDERBOOK] debug: removed all orders for peer 02529a91d073dda641565ef7affccf035905f3d8c88191bdea83a35f37ccce5d64
xud_1        | 09/10/2019 20:34:13.169 [P2P] debug: attempting to reconnect to a disconnected peer 02529a91d073dda641565ef7affccf035905f3d8c88191bdea83a35f37ccce5d64
xud_1        | 09/10/2019 20:34:28.188 [P2P] warn: could not open connection to peer (02529a91d073dda641565ef7affccf035905f3d8c88191bdea83a35f37ccce5d64@xud1.exchangeunion.com:8885): could not connect to peer at xud1.exchangeunion.com:8885: connect ECONNREFUSED 224.0.0.2:8885
xud_1        | 09/10/2019 20:34:30.320 [P2P] debug: Connected pre-handshake to 02529a91d073dda641565ef7affccf035905f3d8c88191bdea83a35f37ccce5d64@rgz5icb5jdxzmu7r7tbis64q23ioytzd4tqikuyb5kz75w75rbe6veyd.onion:8885
xud_1        | 09/10/2019 20:34:30.913 [P2P] debug: received disconnecting packet from 02529a91d073dda641565ef7affccf035905f3d8c88191bdea83a35f37ccce5d64@rgz5icb5jdxzmu7r7tbis64q23ioytzd4tqikuyb5kz75w75rbe6veyd.onion:8885 due to AlreadyConnected
xud_1        | 09/10/2019 20:34:30.967 [P2P] info: Socket closed prior to handshake with 02529a91d073dda641565ef7affccf035905f3d8c88191bdea83a35f37ccce5d64@rgz5icb5jdxzmu7r7tbis64q23ioytzd4tqikuyb5kz75w75rbe6veyd.onion:8885
xud_1        | 09/10/2019 20:34:30.968 [P2P] warn: could not open connection to peer (02529a91d073dda641565ef7affccf035905f3d8c88191bdea83a35f37ccce5d64@rgz5icb5jdxzmu7r7tbis64q23ioytzd4tqikuyb5kz75w75rbe6veyd.onion:8885): Peer 02529a91d073dda641565ef7affccf035905f3d8c88191bdea83a35f37ccce5d64@rgz5icb5jdxzmu7r7tbis64q23ioytzd4tqikuyb5kz75w75rbe6veyd.onion:8885 disconnected from us due to AlreadyConnected
xud_1        | 09/10/2019 20:34:31.300 [P2P] debug: Connected pre-handshake to 02529a91d073dda641565ef7affccf035905f3d8c88191bdea83a35f37ccce5d64@xud1.exchangeunion.com:8885
xud_1        | 09/10/2019 20:34:31.635 [P2P] debug: received disconnecting packet from 02529a91d073dda641565ef7affccf035905f3d8c88191bdea83a35f37ccce5d64@xud1.exchangeunion.com:8885 due to AlreadyConnected
xud_1        | 09/10/2019 20:34:31.637 [P2P] info: Socket closed prior to handshake with 02529a91d073dda641565ef7affccf035905f3d8c88191bdea83a35f37ccce5d64@xud1.exchangeunion.com:8885
xud_1        | 09/10/2019 20:34:31.640 [P2P] warn: could not open connection to peer (02529a91d073dda641565ef7affccf035905f3d8c88191bdea83a35f37ccce5d64@xud1.exchangeunion.com:8885): Peer 02529a91d073dda641565ef7affccf035905f3d8c88191bdea83a35f37ccce5d64@xud1.exchangeunion.com:8885 disconnected from us due to AlreadyConnected
```

**Comment by LePremierHomme** [comment] 2019-12-11 17:57
If the two nodes timeline is synced, It looks like node2 detected the TCP disconnection first, and was attempting to reconnect to node1 which still didn't detect the TCP disconnection, and so received `AlreadyConnected` disconnecting messages. 

But node1 log seems incomplete.
Is this the full version?

**Comment by LePremierHomme** [comment] 2019-12-11 17:59
Is the problem reproducible?

**Comment by erkarl** [comment] 2019-12-11 21:11
> Is this the full version?
No, I truncated the non-relevant lines at the time. Sorry, I no longer have the full logs.

**Comment by LePremierHomme** [comment] 2019-12-11 21:16
Ok, so I think we can close this for now, because if the scenario I described is correct (and we can know this only by having the full logs), I don't think there's much to be done.

**Comment by erkarl** [comment] 2019-12-11 21:25
I'll make sure to include full logs when this comes up again.

**Closed** 2019-12-11 21:25 UTC
Labels: P3, bug, p2p
