### ISSUE TITLE
Matching routine repedeately matching same order

### ISSUE THREAD

**Issue by raladev** [ExchangeUnion/xud#1595] opened 2020-06-02 11:46 UTC
### Precondition
You got No Route Error after installation or you can reliably reproduce it

### Steps to reproduce

1. place buy 1 LTC/BTC 0.001 order as a maker
2. sell 0.1 LTC/BTC mkt 1 as a taker

### Actual behaviour

10 No Route swap attempts with order of maker after  
[Screen](https://user-images.githubusercontent.com/29906866/83516041-095d6780-a4df-11ea-8cf5-dd42d9960b84.png)

After 10 attempts order disappeared from orderbook.

### Expected behaviour

only 1 No Route error per order, after that order should be removed from orderbook and new order should be used for match.

[logs.zip](https://github.com/ExchangeUnion/xud/files/4716883/logs.zip)

**Comment by sangaman** [comment] 2020-06-05 04:36
Just to be clear, is xud from the screenshot being run with the `debug.testing` option?

**Comment by kilrau** [comment] 2020-06-08 15:43
I reproduced that today. After swap failure xud continues the matching routine ending up matching the exact same order again:
```
matched 0.01 ETH @ 0.11 with peer RegularExample order 9e2e53d0-a99c-11ea-940f-e7899c3c4150, attempting swap...
failed to swap 0.01 ETH due to SwapTimedOut with peer order 9e2e53d0-a99c-11ea-940f-e7899c3c4150, continuing with matching routine...
matched 0.01 ETH @ 0.11 with peer RegularExample order e92352a0-a99c-11ea-940f-e7899c3c4150, attempting swap...
```
sometimes it says "no more matches found, entering order book after doing it twice, sometimes 6 times or even endlessly.

**Comment by raladev** [comment] 2020-06-08 15:46
> I reproduced that today. After swap failure xud continues the matching routine ending up matching the exact same order again:
> 
> ```
> matched 0.01 ETH @ 0.11 with peer RegularExample order 9e2e53d0-a99c-11ea-940f-e7899c3c4150, attempting swap...
> failed to swap 0.01 ETH due to SwapTimedOut with peer order 9e2e53d0-a99c-11ea-940f-e7899c3c4150, continuing with matching routine...
> matched 0.01 ETH @ 0.11 with peer RegularExample order e92352a0-a99c-11ea-940f-e7899c3c4150, attempting swap...
> ```
> 
> sometimes only once before stopping with "no more matches found, order entered order book as". Sometimes 4-5 times matching with the exact same order, sometimes endlessly.

count of errors based on qty, for instance, maker's order is buy 0.9 eth/btc and you place sell 0.1 eth/btc mkt -> you will got the error nine times.

**Comment by sangaman** [comment] 2020-06-09 07:42
Indeed the issue here is that when a portion of an order fails, we only remove that portion of the order from the order book. If an order to sell 1 LTC is matched with an order in the order book to sell 10 LTC, each match/swap that fails will remove 1 LTC from the 10 in the book.

That's how it was designed but thinking about it now it doesn't make much sense. It would indeed make sense to remove the entire order if any part of it fails, that will just involve more than the matching logic (which removes orders or parts of orders as they're matched). I'll have a fix ready to test soon.

**Comment by sangaman** [comment] 2020-06-11 04:57
Resolving this issue is not easy and when I delved into it I remembered why we left this as it is while working on the order book and matching.

Each side of an order book is a heap where we can get the order with the best price quickly but "looking past" the best order isn't practical since the collection of orders isn't completely sorted. My initial approach, which was to track which peer orders have already failed to skip them when repeating the matching process, doesn't work for this reason. Instead there are several different viable approaches and I'm not sure which to proceed with.

1. When part of an order fails a swap, remove the entire order from the order book and not just the portion that failed. This is probably the simplest approach and my preferred one, but it might be a bit drastic.

2. Temporarily remove an order from the order book when any part of it fails a swap, and add it back to the order book when all matching is complete for the order we placed that failed to swap with it. This behavior is similar to what the `debug.testing` option does to matching, and in fact the simplest approach would just be to make this behavior the standard. Orders we can't swap with would stay in the order book until or unless we banned the peer that placed them, however, which isn't ideal. It also could result in some slightly strange behavior if we're trying to match/swap two orders at once with them stepping on each others toes.

3. Change the structure of the order book to always be sorted, enabling the approach of peeking beyond the orders that we've already attempted and failed. This isn't great for performance, but until or unless we're regularly dealing with hundreds or thousands of orders it should suffice.

**Comment by kilrau** [comment] 2020-06-11 10:17
On my side reproduced this **without** setting `debug.testing` in `xud.conf`. U @raladev ?

**Comment by raladev** [comment] 2020-06-11 10:27
> On my side this happened with the default setup (**without** setting `debug.testing` in `xud.conf`). I guess for u too @raladev ?

Yeap, same for me, it was reproduced without debug option with default setup.

**Comment by kilrau** [comment] 2020-06-11 10:35
Guess that was clear by now, but I can confirm that the repeated swap attempts continue trying to fillall available quantity of an order. If my order tries to fill all available quantity, there is not repeated swap attempt.

Example: Trying to fill qty 0.8 with 0.2 leads to 4x swap attempt:
```
Trading pair: LTC/BTC
┌────────────────────────────────────────────────┬────────────────────────────────────────────────┐
│ Buy                                            │ Sell                                           │
├───────────────┬─────────────┬──────────────────┼───────────────┬─────────────┬──────────────────┤
│ Quantity      │ Price       │ Alias            │ Quantity      │ Price       │ Alias            │
├───────────────┼─────────────┼──────────────────┼───────────────┼─────────────┼──────────────────┤
│ 0.9           │ 0.089       │ LaundryBrush     │ 0.8           │ 0.111       │ LaundryBrush     │
└───────────────┴─────────────┴──────────────────┴───────────────┴─────────────┴──────────────────┘
simnet > buy 0.2 ltc/btc 0.111
matched 0.2 LTC @ 0.111 with peer LaundryBrush order f6280290-aaf8-11ea-9608-d95f7c6bb21e, attempting swap...
failed to swap 0.2 LTC due to UnexpectedClientError with peer order f6280290-aaf8-11ea-9608-d95f7c6bb21e, continuing with matching routine...
matched 0.2 LTC @ 0.111 with peer LaundryBrush order f6280290-aaf8-11ea-9608-d95f7c6bb21e, attempting swap...
failed to swap 0.2 LTC due to UnexpectedClientError with peer order f6280290-aaf8-11ea-9608-d95f7c6bb21e, continuing with matching routine...
matched 0.2 LTC @ 0.111 with peer LaundryBrush order f6280290-aaf8-11ea-9608-d95f7c6bb21e, attempting swap...
failed to swap 0.2 LTC due to UnexpectedClientError with peer order f6280290-aaf8-11ea-9608-d95f7c6bb21e, continuing with matching routine...
matched 0.2 LTC @ 0.111 with peer LaundryBrush order f6280290-aaf8-11ea-9608-d95f7c6bb21e, attempting swap...
failed to swap 0.2 LTC due to UnexpectedClientError with peer order f6280290-aaf8-11ea-9608-d95f7c6bb21e, continuing with matching routine...
remaining 0.2 LTC entered the order book as af415ad0-abce-11ea-92b8-b1368d768321
```
Trying to fill qty 0.8 with 0.8 doesn't cause another swap attempt:
```
Trading pair: LTC/BTC
┌────────────────────────────────────────────────┬────────────────────────────────────────────────┐
│ Buy                                            │ Sell                                           │
├───────────────┬─────────────┬──────────────────┼───────────────┬─────────────┬──────────────────┤
│ Quantity      │ Price       │ Alias            │ Quantity      │ Price       │ Alias            │
├───────────────┼─────────────┼──────────────────┼───────────────┼─────────────┼──────────────────┤
│ 0.9           │ 0.089       │ LaundryBrush     │ 0.8           │ 0.111       │ LaundryBrush     │
└───────────────┴─────────────┴──────────────────┴───────────────┴─────────────┴──────────────────┘
simnet > buy 0.8 ltc/btc 0.111
matched 0.8 LTC @ 0.111 with peer LaundryBrush order f6280290-aaf8-11ea-9608-d95f7c6bb21e, attempting swap...
failed to swap 0.8 LTC due to UnexpectedClientError with peer order f6280290-aaf8-11ea-9608-d95f7c6bb21e, continuing with matching routine...
remaining 0.8 LTC entered the order book as 6dce7100-abce-11ea-91a3-2f731d7548ef
```

**Comment by erkarl** [comment] 2020-06-11 11:04
> Resolving this issue is not easy and when I delved into it I remembered why we left this as it is while working on the order book and matching.
> 
> Each side of an order book is a heap where we can get the order with the best price quickly but "looking past" the best order isn't practical since the collection of orders isn't completely sorted. My initial approach, which was to track which peer orders have already failed to skip them when repeating the matching process, doesn't work for this reason. Instead there are several different viable approaches and I'm not sure which to proceed with.
> 
>     1. When part of an order fails a swap, remove the entire order from the order book and not just the portion that failed. This is probably the simplest approach and my preferred one, but it might be a bit drastic.
> 
>     2. Temporarily remove an order from the order book when any part of it fails a swap, and add it back to the order book when all matching is complete for the order we placed that failed to swap with it. This behavior is similar to what the `debug.testing` option does to matching, and in fact the simplest approach would just be to make this behavior the standard. Orders we can't swap with would stay in the order book until or unless we banned the peer that placed them, however, which isn't ideal. It also could result in some slightly strange behavior if we're trying to match/swap two orders at once with them stepping on each others toes.
> 
>     3. Change the structure of the order book to always be sorted, enabling the approach of peeking beyond the orders that we've already attempted and failed. This isn't great for performance, but until or unless we're regularly dealing with hundreds or thousands of orders it should suffice.

In the short term option 1 looks appealing. In the longer term option 2 is probably better. My concern is that implementing option 2 is probably more time consuming and error prone than 1.

**Comment by kilrau** [comment] 2020-06-11 11:09
I believe @sangaman would just make the current behavior of `debug.testing` the default. We certainly had to test this a bit more beforehand, but afaik it wouldn't require much additional implementation. Let's bring this up on the call today.

**Closed** 2020-07-19 09:45 UTC
Labels: P1, bug, order book, swaps
