### ISSUE TITLE
Hold amount fixes

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#640] opened 2018-11-06 15:54 UTC
- Swap amount holding is missing when initiating the swap deal (taker)
- Matching engine does not check the amount held when matching
- Held amounts should be presented as part of order book e.g. in orange with added `(⇄)` or `(swapping)` after quantity

**Comment by sangaman** [comment] 2018-11-06 16:09
There's no hold as the taker because the order has not entered the order book nor shared with peers yet. I don't think this is a bug, it's by design.

I'm not sure what you mean by your second point, is this still referring to the the taker `placeOrder` logic? We wait until a swap fails or succeeds already and only attempt another match/swap if one fails.

For the third point I think this would not be particularly helpful info to display. The hold does not apply at all to peer orders - which should be the majority of the orders displayed - and the holds on own orders are temporary and can change from second to second. By the time you see it, it could easily already have changed. If we're interested in the data for debugging/testing purposes only we can output the json data directly.

**Comment by offerm** [comment] 2018-11-09 13:50
#1 - agreed.
#2 - no issue for now.
#3 - lets wait and see if this is needed.

Closing

**Closed** 2018-11-13 17:09 UTC
Labels: critical bug, swaps, top priority
