### ISSUE TITLE
Exchange cltvDelta related info when initializing a session with peer

### ISSUE THREAD

**Issue by erkarl** [ExchangeUnion/xud#1162] opened 2019-08-18 09:14 UTC
When the taker executes a swap the first step is to verify `makerOrder` and `takerOrder`. This includes a `getRoutes` request: <https://github.com/ExchangeUnion/xud/blob/master/lib/swaps/Swaps.ts#L274>

@offerm pointed out:
> The queryroutes by the taker is simply not needed.  It does not give value if we are not using the right cltv_delta which we don't know at this stage. So we have options:
> Actually, only reasonable option is to drop this query routes.

@sangaman's opinion:
> i think it is useful, because if it doesn't find a route, we know that a swap is impossible. it rules out attempts that are sure to fail

**Comment by kilrau** [comment] 2019-08-19 12:30
I also believe it's useful, since it avoids starting a swap that will fail for sure. Trade-off is speed: it slows down swap execution a little bit. Let's discuss it on the call.

**Comment by kilrau** [comment] 2019-08-19 13:08
Let's also discuss on the call if the first `QueryRoutes` is needed. I believe it is.

**Comment by kilrau** [comment] 2019-08-19 14:19
Related: https://github.com/ExchangeUnion/xud/issues/1164

**Comment by kilrau** [comment] 2019-08-19 14:34
@offerm  
* only exchange taker's cltv delta
* via swap packets on every swap

**Comment by kilrau** [comment] 2019-08-19 14:37
> Let's also discuss on the call if the first QueryRoutes is needed. I believe it is.

Keep it.

**Comment by sangaman** [comment] 2019-08-21 08:23
I like the core premise of exchanging cltv delta values as part of the node state rather than as part of each swap request packet. It's a low priority enhancement but nice to have nevertheless.

**Comment by kilrau** [comment] 2019-10-09 17:30
Since we decided to keep `QueryRoutes` this issue is about "Exchange cltvDelta related info when initializing a session " and a duplicate of https://github.com/ExchangeUnion/xud/issues/953. Closing.

**Closed by kilrau** 2019-10-09 17:30 UTC
