### ISSUE TITLE
[Crash] Nodejs 8.11.3 LTS crashes xud, v9.2.1 & v10.8.0 works

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#251] opened 2018-08-02 05:31 UTC
Nodejs 8.11.3 LTS produces

```bash
TypeError: Cannot read property 'write' of undefined
    at Peer.sendRaw (/home/kilrau/xud/dist/p2p/Peer.js:124:25)
    at Peer.sendPacket (/home/kilrau/xud/dist/p2p/Peer.js:109:18)
    at Peer.sendOrders (/home/kilrau/xud/dist/p2p/Peer.js:117:18)
    at Promise.all.then (/home/kilrau/xud/dist/orderbook/OrderBook.js:232:22)
    at <anonymous>
/home/kilrau/xud/dist/bootstrap.js:13
        throw err;
        ^

TypeError: Cannot read property 'write' of undefined
    at Peer.sendRaw (/home/kilrau/xud/dist/p2p/Peer.js:124:25)
    at Peer.sendPacket (/home/kilrau/xud/dist/p2p/Peer.js:109:18)
    at Peer.sendOrders (/home/kilrau/xud/dist/p2p/Peer.js:117:18)
    at Promise.all.then (/home/kilrau/xud/dist/orderbook/OrderBook.js:232:22)
    at <anonymous>
```
and causes xud to crash. Maybe the write property of the socket is not available in Nodejs 8.11.3 LTS?

Must be a PR from today...

**Comment by sangaman** [comment] 2018-08-02 12:33
I've seen this before on my own, I don't think it's related to the node version. Marking this as a duplicate of #253.

**Closed by sangaman** 2018-08-02 12:33 UTC
Labels: bug, duplicate, mid priority
