### ISSUE TITLE
No route - repeat swap attempt 

### ISSUE THREAD

**Issue by offerm** [ExchangeUnion/xud#1004] opened 2019-06-02 20:51 UTC
test2 node does not have an LTC channels. Sanity swap is off.

Order is 
```
xud@xud-test-2:~$ xucli sell 0.001 LTC/BTC 0.0077 
failed to swap 0.001 LTC with peer order 59504a20-8576-11e9-8772-b1e9a3fc91a3
remaining 0.001 LTC entered the order book as b51099f0-8576-11e9-8035-ede487fe967d
```

Log shows (total 4478 times):
```
02/06/2019 20:40:50.191 [ORDERBOOK] debug: reduced order 59504a20-8576-11e9-8772-b1e9a3fc91a3 by 100000 quantity while matching order b51099f0-8576-11e9-8035-ede487fe967d
02/06/2019 20:40:50.198 [ORDERBOOK] debug: matched with peer 02b66438730d1fcdf4a4ae5d3d73e847a272f160fee2938e132b52cab0a0d9cfc6, executing swap on taker b51099f0-8576-11e9-8035-ede487fe967d and maker 5950
4a20-8576-11e9-8772-b1e9a3fc91a3 for 100000
02/06/2019 20:40:50.222 [ORDERBOOK] error: swap between orders 59504a20-8576-11e9-8772-b1e9a3fc91a3 & b51099f0-8576-11e9-8035-ede487fe967d failed due to NoRouteFound
02/06/2019 20:40:50.223 [ORDERBOOK] warn: swap for 100000 failed during order matching due to NoRouteFound, will repeat matching routine for failed quantity
02/06/2019 20:40:50.224 [ORDERBOOK] debug: repeating matching routine for b51099f0-8576-11e9-8035-ede487fe967d for failed quantity of 100000
02/06/2019 20:40:50.225 [ORDERBOOK] debug: reduced order 59504a20-8576-11e9-8772-b1e9a3fc91a3 by 100000 quantity while matching order b51099f0-8576-11e9-8035-ede487fe967d
02/06/2019 20:40:50.226 [ORDERBOOK] debug: matched with peer 02b66438730d1fcdf4a4ae5d3d73e847a272f160fee2938e132b52cab0a0d9cfc6, executing swap on taker b51099f0-8576-11e9-8035-ede487fe967d and maker 59504a20-8576-11e9-8772-b1e9a3fc91a3 for 100000
02/06/2019 20:40:50.232 [ORDERBOOK] error: swap between orders 59504a20-8576-11e9-8772-b1e9a3fc91a3 & b51099f0-8576-11e9-8035-ede487fe967d failed due to NoRouteFound
02/06/2019 20:40:50.233 [ORDERBOOK] warn: swap for 100000 failed during order matching due to NoRouteFound, will repeat matching routine for failed quantity
02/06/2019 20:40:50.234 [ORDERBOOK] debug: repeating matching routine for b51099f0-8576-11e9-8035-ede487fe967d for failed quantity of 100000
02/06/2019 20:40:50.240 [ORDERBOOK] debug: reduced order 59504a20-8576-11e9-8772-b1e9a3fc91a3 by 100000 quantity while matching order b51099f0-8576-11e9-8035-ede487fe967d
02/06/2019 20:40:50.241 [ORDERBOOK] debug: matched with peer 02b66438730d1fcdf4a4ae5d3d73e847a272f160fee2938e132b52cab0a0d9cfc6, executing swap on taker b51099f0-8576-11e9-8035-ede487fe967d and maker 59504a20-8576-11e9-8772-b1e9a3fc91a3 for 100000
02/06/2019 20:40:50.247 [ORDERBOOK] error: swap between orders 59504a20-8576-11e9-8772-b1e9a3fc91a3 & b51099f0-8576-11e9-8035-ede487fe967d failed due to NoRouteFound
02/06/2019 20:40:50.248 [ORDERBOOK] warn: swap for 100000 failed during order matching due to NoRouteFound, will repeat matching routine for failed quantity
02/06/2019 20:40:50.249 [ORDERBOOK] debug: repeating matching routine for b51099f0-8576-11e9-8035-ede487fe967d for failed quantity of 100000
02/06/2019 20:40:50.249 [ORDERBOOK] debug: reduced order 59504a20-8576-11e9-8772-b1e9a3fc91a3 by 100000 quantity while matching order b51099f0-8576-11e9-8035-ede487fe967d
02/06/2019 20:40:50.250 [ORDERBOOK] debug: matched with peer 02b66438730d1fcdf4a4ae5d3d73e847a272f160fee2938e132b52cab0a0d9cfc6, executing swap on taker b51099f0-8576-11e9-8035-ede487fe967d and maker 59504a20-8576-11e9-8772-b1e9a3fc91a3 for 100000
02/06/2019 20:40:50.256 [ORDERBOOK] error: swap between orders 59504a20-8576-11e9-8772-b1e9a3fc91a3 & b51099f0-8576-11e9-8035-ede487fe967d failed due to NoRouteFound
02/06/2019 20:40:50.257 [ORDERBOOK] warn: swap for 100000 failed during order matching due to NoRouteFound, will repeat matching routine for failed quantity
02/06/2019 20:40:50.257 [ORDERBOOK] debug: repeating matching routine for b51099f0-8576-11e9-8035-ede487fe967d for failed quantity of 100000
02/06/2019 20:40:50.258 [ORDERBOOK] debug: reduced order 59504a20-8576-11e9-8772-b1e9a3fc91a3 by 100000 quantity while matching order b51099f0-8576-11e9-8035-ede487fe967d
02/06/2019 20:40:50.258 [ORDERBOOK] debug: matched with peer 02b66438730d1fcdf4a4ae5d3d73e847a272f160fee2938e132b52cab0a0d9cfc6, executing swap on taker b51099f0-8576-11e9-8035-ede487fe967d and maker 59504a20-8576-11e9-8772-b1e9a3fc91a3 for 100000
02/06/2019 20:40:50.263 [ORDERBOOK] error: swap between orders 59504a20-8576-11e9-8772-b1e9a3fc91a3 & b51099f0-8576-11e9-8035-ede487fe967d failed due to NoRouteFound
02/06/2019 20:40:50.264 [ORDERBOOK] warn: swap for 100000 failed during order matching due to NoRouteFound, will repeat matching routine for failed quantity
02/06/2019 20:40:50.264 [ORDERBOOK] debug: repeating matching routine for b51099f0-8576-11e9-8035-ede487fe967d for failed quantity of 100000
02/06/2019 20:40:50.265 [ORDERBOOK] debug: reduced order 59504a20-8576-11e9-8772-b1e9a3fc91a3 by 100000 quantity while matching order b51099f0-8576-11e9-8035-ede487fe967d
02/06/2019 20:40:50.265 [ORDERBOOK] debug: matched with peer 02b66438730d1fcdf4a4ae5d3d73e847a272f160fee2938e132b52cab0a0d9cfc6, executing swap on taker b51099f0-8576-11e9-8035-ede487fe967d and maker 59504a20-8576-11e9-8772-b1e9a3fc91a3 for 100000
02/06/2019 20:40:50.270 [ORDERBOOK] error: swap between orders 59504a20-8576-11e9-8772-b1e9a3fc91a3 & b51099f0-8576-11e9-8035-ede487fe967d failed due to NoRouteFound
02/06/2019 20:40:50.270 [ORDERBOOK] warn: swap for 100000 failed during order matching due to NoRouteFound, will repeat matching routine for failed quantity
02/06/2019 20:40:50.271 [ORDERBOOK] debug: repeating matching routine for b51099f0-8576-11e9-8035-ede487fe967d for failed quantity of 100000
02/06/2019 20:40:50.271 [ORDERBOOK] debug: reduced order 59504a20-8576-11e9-8772-b1e9a3fc91a3 by 100000 quantity while matching order b51099f0-8576-11e9-8035-ede487fe967d
02/06/2019 20:40:50.272 [ORDERBOOK] debug: matched with peer 02b66438730d1fcdf4a4ae5d3d73e847a272f160fee2938e132b52cab0a0d9cfc6, executing swap on taker b51099f0-8576-11e9-8035-ede487fe967d and maker 59504a20-8576-11e9-8772-b1e9a3fc91a3 for 100000
02/06/2019 20:40:50.276 [ORDERBOOK] error: swap between orders 59504a20-8576-11e9-8772-b1e9a3fc91a3 & b51099f0-8576-11e9-8035-ede487fe967d failed due to NoRouteFound
02/06/2019 20:40:50.277 [ORDERBOOK] warn: swap for 100000 failed during order matching due to NoRouteFound, will repeat matching routine for failed quantity
02/06/2019 20:40:50.278 [ORDERBOOK] debug: repeating matching routine for b51099f0-8576-11e9-8035-ede487fe967d for failed quantity of 100000
02/06/2019 20:40:50.278 [ORDERBOOK] debug: reduced order 59504a20-8576-11e9-8772-b1e9a3fc91a3 by 100000 quantity while matching order b51099f0-8576-11e9-8035-ede487fe967d
02/06/2019 20:40:50.279 [ORDERBOOK] debug: matched with peer 02b66438730d1fcdf4a4ae5d3d73e847a272f160fee2938e132b52cab0a0d9cfc6, executing swap on taker b51099f0-8576-11e9-8035-ede487fe967d and maker 59504a20-8576-11e9-8772-b1e9a3fc91a3 for 100000
...
...
...
...
02/06/2019 20:41:00.182 [ORDERBOOK] error: swap between orders 59504a20-8576-11e9-8772-b1e9a3fc91a3 & b51099f0-8576-11e9-8035-ede487fe967d failed due to NoRouteFound
02/06/2019 20:41:00.183 [ORDERBOOK] warn: swap for 100000 failed during order matching due to NoRouteFound, will repeat matching routine for failed quantity
02/06/2019 20:41:00.183 [ORDERBOOK] debug: repeating matching routine for b51099f0-8576-11e9-8035-ede487fe967d for failed quantity of 100000
02/06/2019 20:41:00.183 [ORDERBOOK] debug: reduced order 59504a20-8576-11e9-8772-b1e9a3fc91a3 by 100000 quantity while matching order b51099f0-8576-11e9-8035-ede487fe967d
02/06/2019 20:41:00.183 [ORDERBOOK] debug: matched with peer 02b66438730d1fcdf4a4ae5d3d73e847a272f160fee2938e132b52cab0a0d9cfc6, executing swap on taker b51099f0-8576-11e9-8035-ede487fe967d and maker 59504a20-8576-11e9-8772-b1e9a3fc91a3 for 100000
02/06/2019 20:41:00.185 [ORDERBOOK] error: swap between orders 59504a20-8576-11e9-8772-b1e9a3fc91a3 & b51099f0-8576-11e9-8035-ede487fe967d failed due to NoRouteFound
02/06/2019 20:41:00.186 [ORDERBOOK] warn: swap for 100000 failed during order matching due to NoRouteFound, will repeat matching routine for failed quantity
02/06/2019 20:41:00.186 [ORDERBOOK] debug: repeating matching routine for b51099f0-8576-11e9-8035-ede487fe967d for failed quantity of 100000
02/06/2019 20:41:00.186 [ORDERBOOK] debug: reduced order 59504a20-8576-11e9-8772-b1e9a3fc91a3 by 100000 quantity while matching order b51099f0-8576-11e9-8035-ede487fe967d
02/06/2019 20:41:00.186 [ORDERBOOK] debug: matched with peer 02b66438730d1fcdf4a4ae5d3d73e847a272f160fee2938e132b52cab0a0d9cfc6, executing swap on taker b51099f0-8576-11e9-8035-ede487fe967d and maker 59504a20-8576-11e9-8772-b1e9a3fc91a3 for 100000
02/06/2019 20:41:00.188 [ORDERBOOK] error: swap between orders 59504a20-8576-11e9-8772-b1e9a3fc91a3 & b51099f0-8576-11e9-8035-ede487fe967d failed due to NoRouteFound
02/06/2019 20:41:00.188 [ORDERBOOK] warn: swap for 100000 failed during order matching due to NoRouteFound, will repeat matching routine for failed quantity
02/06/2019 20:41:00.189 [ORDERBOOK] debug: repeating matching routine for b51099f0-8576-11e9-8035-ede487fe967d for failed quantity of 100000
02/06/2019 20:41:00.189 [ORDERBOOK] debug: reduced order 59504a20-8576-11e9-8772-b1e9a3fc91a3 by 100000 quantity while matching order b51099f0-8576-11e9-8035-ede487fe967d
02/06/2019 20:41:00.189 [ORDERBOOK] debug: matched with peer 02b66438730d1fcdf4a4ae5d3d73e847a272f160fee2938e132b52cab0a0d9cfc6, executing swap on taker b51099f0-8576-11e9-8035-ede487fe967d and maker 59504a20-8576-11e9-8772-b1e9a3fc91a3 for 100000
02/06/2019 20:41:00.191 [ORDERBOOK] error: swap between orders 59504a20-8576-11e9-8772-b1e9a3fc91a3 & b51099f0-8576-11e9-8035-ede487fe967d failed due to NoRouteFound
02/06/2019 20:41:00.191 [ORDERBOOK] warn: swap for 100000 failed during order matching due to NoRouteFound, will repeat matching routine for failed quantity
02/06/2019 20:41:00.192 [ORDERBOOK] debug: repeating matching routine for b51099f0-8576-11e9-8035-ede487fe967d for failed quantity of 100000
02/06/2019 20:41:00.192 [ORDERBOOK] debug: placeOrder max time exceeded. order ({"pairId":"LTC/BTC","price":0.0077,"quantity":100000,"isBuy":false,"localId":"b51099f0-8576-11e9-8035-ede487fe967d","hold":0,"id":"b51099f0-8576-11e9-8035-ede487fe967d","initialQuantity":100000,"createdAt":1559508050191}) won't be fully matched
02/06/2019 20:41:00.209 [ORDERBOOK] debug: order added: {"pairId":"LTC/BTC","price":0.0077,"quantity":100000,"isBuy":false,"localId":"b51099f0-8576-11e9-8035-ede487fe967d","hold":0,"id":"b51099f0-8576-11e9-8035-ede487fe967d","initialQuantity":100000,"createdAt":1559508050191}
```

**Comment by sangaman** [comment] 2019-06-04 16:13
I'm not sure this is exactly a "bug" per se, this is the intended behavior currently even though it's certainly not ideal. I think this relates to #684, and basically we need to more intelligently handle repeated routing/payment failures with a particular peer and go the route of deactivating pairs. The tricky part is that without sanity swaps, I'm not sure when we'd determine when to reactive a pair with a peer. Maybe, even if `nosanitychecks` is set, we use sanity swaps only when determining when to reactivate pairs - so we start with pairs active by default without a sanity swap to start.

**Comment by kilrau** [comment] 2019-06-05 09:49
> Sanity swap is off

Do you mean `sanitychecks=false`? If so, this also switches off @erkarl 's sanity checks on place order which would have caught this one. @offerm

**Comment by offerm** [comment] 2019-06-05 11:58
Sure, sanity checks can prevent this but can;t eliminate the problem
completely.  It is easy to create this setup after the sanity checks were
already done.

Looking for a route 4500 times and blocking/Slowing XUD during that time
does not make a lot of sense. Suggest we look for the reason for this and
not what may prevent this from happening.

Also, maybe we should not hide all checks behind the same flag to allow
turning them ON separately.

**Comment by kilrau** [comment] 2019-06-06 09:18
> Also, maybe we should not hide all checks behind the same flag to allow turning them ON separately

Had the same thought. But since this a debug feature, we might want to hide this somewhere in `debug` or `developer` config category which is clearly marked as "Don't touch, if you don't know what you are doing!"

**Comment by kilrau** [comment] 2019-06-07 09:15
Volunteers? e.g. @ImmanuelSegol ?

**Comment by kilrau** [comment] 2019-06-11 08:54
Lucky you! @erkarl

**Comment by flicker-harmony** [comment] 2020-02-11 14:06
Pls provide estimate for this task.

**Comment by engwarrior** [comment] 2020-02-11 14:08
Pls provide estimate for this task.

**Closed** 2020-10-19 11:42 UTC
Labels: 101-250 XUC, P2, bug, swaps
