### ISSUE TITLE
channelbalance - need more digits

### ISSUE THREAD

**Issue by offerm** [ExchangeUnion/xud#1217] opened 2019-09-10 19:27 UTC
Need to show more digits - specially on mainnet

```
Channel balance:
┌────────┬─────────┬─────────────────┐
│ Ticker │ Balance │ Pending Balance │
├────────┼─────────┼─────────────────┤
│ BTC    │ 0.002   │ 0               │
├────────┼─────────┼─────────────────┤
│ DAI    │ 0       │ 0               │
├────────┼─────────┼─────────────────┤
│ WETH   │ 0       │ 0               │
└────────┴─────────┴─────────────────┘
```

**Comment by kilrau** [comment] 2019-09-18 15:35
> Or is the balance actually greater than 0.002 and it's not being displayed?

That's what I assume @offerm means. I tried reproducing this, but couldn't. Could you help out with `xucli getbalance` vs. `lncli channelbalance` outputs? @offerm

**Comment by kilrau** [comment] 2019-10-10 13:15
1. cli command is `getbalance` :)
2. check if the output cuts non-0 digits, e.g. in @offerm example his actual balance is `0.0021` whereas only `0.002` is displayed.If you cannot find this is the case, we can close.

**Comment by rsercano** [comment] 2019-10-10 13:23
got it, thanks Kilian will check that @kilrau

**Comment by sangaman** [comment] 2019-10-10 14:21
FWIW, I'm pretty sure it doesn't cut non-0 digits - we have tests for that. I suspect we can close this issue unless there's something else to it.

**Closed** 2019-10-11 11:54 UTC
Labels: P3, bug, good first issue, help wanted

**Comment by kilrau** [comment] 2019-10-11 11:58
I checked several different balances on my node and couldn't find any cutting of non-0 digits neither. And since we have tests, I'm closing to not spend more time on this and trying to figure out what's wrong. Let's be more concise in the issue description from now on :) @offerm
