### ISSUE TITLE
getInfo call shows Connext ready when it's not

### ISSUE THREAD

**Issue by rsercano** [ExchangeUnion/xud#2038] opened 2020-12-12 08:01 UTC
I'm working with current `master` branch, connext is down now, as in the picture:
![image](https://user-images.githubusercontent.com/3640368/101978874-680f5500-3c69-11eb-8ea2-26b77a5ab0a7.png)

But my getInfo call returns it's Ready:
![image](https://user-images.githubusercontent.com/3640368/101978876-7198bd00-3c69-11eb-8de6-7d7dea36d50e.png)

**Comment by kilrau** [comment] 2020-12-14 11:34
Many thanks for the issue (and especially the fix!) :+1:

**Comment by raladev** [comment] 2020-12-14 13:16
duplicate of https://github.com/ExchangeUnion/xud/issues/2031, closing 2031.

**Closed** 2020-12-21 11:12 UTC
Labels: P3, bug
