### ISSUE TITLE
xud1,2,3 - simnet not connected

### ISSUE THREAD

**Issue by offerm** [ExchangeUnion/xud#1330] opened 2019-11-11 05:47 UTC
The seed nodes on simnet does not connect each other.

Looks like these node try to connect using tor 

```
11/11/2019 05:35:55.932 [P2P] warn: could not open connection to outbound peer (02f9ec3ce1eaa98c19bfb4bc7a374854182191daafbfc83e28d04365212d42d35f@mrkspuomrk37zi4euy474gxaapcs2b26u37qm
4qhmjwuvnbpq5o5k3yd.onion:8885): could not connect to peer at mrkspuomrk37zi4euy474gxaapcs2b26u37qm4qhmjwuvnbpq5o5k3yd.onion:8885: getaddrinfo ENOTFOUND mrkspuomrk37zi4euy474gxaapcs2b2
6u37qm4qhmjwuvnbpq5o5k3yd.onion mrkspuomrk37zi4euy474gxaapcs2b26u37qm4qhmjwuvnbpq5o5k3yd.onion:8885
11/11/2019 05:35:55.934 [P2P] warn: could not open connection to outbound peer (03cc8b36e468309adf9e9f64288d509e993bb2c7cc674afe7ee4b18af7cb09d530@wo3fbmiaekbuf2jgqaxjolsqfzoapovxyqfwn
oktsmynkmypdorxtdad.onion:8885): could not connect to peer at wo3fbmiaekbuf2jgqaxjolsqfzoapovxyqfwnoktsmynkmypdorxtdad.onion:8885: getaddrinfo ENOTFOUND wo3fbmiaekbuf2jgqaxjolsqfzoapov
xyqfwnoktsmynkmypdorxtdad.onion wo3fbmiaekbuf2jgqaxjolsqfzoapovxyqfwnoktsmynkmypdorxtdad.onion:8885
11/11/2019 05:35:55.935 [P2P] warn: could not open connection to outbound peer (0374a988539d10bd91ddf17ef0c1b29cd0589713d6196d1ec1ce078c02b5c16c84@jdzsnahftf6gxm34eufbu6iylju7gzm5fm4gj
7fvqfzndwqvijtm2wid.onion:8885): could not connect to peer at jdzsnahftf6gxm34eufbu6iylju7gzm5fm4gj7fvqfzndwqvijtm2wid.onion:8885: getaddrinfo ENOTFOUND jdzsnahftf6gxm34eufbu6iylju7gzm
5fm4gj7fvqfzndwqvijtm2wid.onion jdzsnahftf6gxm34eufbu6iylju7gzm5fm4gj7fvqfzndwqvijtm2wid.onion:8885
11/11/2019 05:35:55.936 [P2P] warn: could not open connection to outbound peer (035d3ce9c50c9040310f2671a6ea777ff8aa556b8a94ce30577c0f5958537198de@l3n2uhappes7wzjkamhg7ckrm7y2dpdlx6mew
gguxyvmei7y3354egad.onion:8885): could not connect to peer at l3n2uhappes7wzjkamhg7ckrm7y2dpdlx6mewgguxyvmei7y3354egad.onion:8885: getaddrinfo ENOTFOUND l3n2uhappes7wzjkamhg7ckrm7y2dpd
lx6mewgguxyvmei7y3354egad.onion l3n2uhappes7wzjkamhg7ckrm7y2dpdlx6mewgguxyvmei7y3354egad.onion:8885
11/11/2019 05:35:55.938 [P2P] warn: could not open connection to outbound peer (02c7993a5c11507fa8fe2180b114843eab52e0682b4a5b59566f13f084ef5624cb@vltm2xnyzcscx34nozspykn5zc7lvf7foh6yh
wbpifwc4w6urwwm4gad.onion:8885): could not connect to peer at vltm2xnyzcscx34nozspykn5zc7lvf7foh6yhwbpifwc4w6urwwm4gad.onion:8885: getaddrinfo ENOTFOUND vltm2xnyzcscx34nozspykn5zc7lvf7
foh6yhwbpifwc4w6urwwm4gad.onion vltm2xnyzcscx34nozspykn5zc7lvf7foh6yhwbpifwc4w6urwwm4gad.onion:8885
11/11/2019 05:35:55.939 [P2P] warn: could not open connection to outbound peer (0257c02af46a3b231a7341a221f1b3787e0d539699cce25f4ed8532f739f4674f9@dsfkun7v2iqbnxt5fnytlp4u2k5zqgsnaythy
yhomhhmaf6weayxb7qd.onion:8885): could not connect to peer at dsfkun7v2iqbnxt5fnytlp4u2k5zqgsnaythyyhomhhmaf6weayxb7qd.onion:8885: getaddrinfo ENOTFOUND dsfkun7v2iqbnxt5fnytlp4u2k5zqgs
naythyyhomhhmaf6weayxb7qd.onion dsfkun7v2iqbnxt5fnytlp4u2k5zqgsnaythyyhomhhmaf6weayxb7qd.onion:8885
11/11/2019 05:35:55.940 [P2P] warn: could not open connection to outbound peer (02deaa134badbb1c9c75ad96e58b5aef2edde3ab8f61612cb5db8cb809590f3a6e@vn6h33fgqrmv2fpchxpzi6qtknkjxxsxhi6xd
ygu4f7dqciwbdna67qd.onion:8885): could not connect to peer at vn6h33fgqrmv2fpchxpzi6qtknkjxxsxhi6xdygu4f7dqciwbdna67qd.onion:8885: getaddrinfo ENOTFOUND vn6h33fgqrmv2fpchxpzi6qtknkjxxs
xhi6xdygu4f7dqciwbdna67qd.onion vn6h33fgqrmv2fpchxpzi6qtknkjxxsxhi6xdygu4f7dqciwbdna67qd.onion:8885
```

**Comment by kilrau** [comment] 2019-11-12 12:31
That's bad. The expected behavior would be:
* try to connect to TOR once on startup, fail (will be fixed in https://github.com/ExchangeUnion/xud/issues/1154)
* then connect to hardcoded hardcoded clearnet addresses `xud[1,2,3].simnet.exchangeunion.com`

Reproduce by sshing into xud1,2,3.

**Comment by kilrau** [comment] 2019-11-12 17:21
Are you takin gthis one? @sangaman

**Comment by sangaman** [comment] 2019-11-21 15:45
After quite a bit of debugging/testing, I'm pretty sure that the desired behavior works as intended, the issue with these seed nodes is that the only listening addresses they know of for those nodes with warnings above are tor addresses. I'm guessing that the tor nodes do not advertise their clearnet addresses, which makes sense because doing so would defeat the purpose of using tor in the first place. The seed nodes *do* connect to each other, though.

One thing to note is that the seed nodes on simnet do not have hardcoded tor addresses and they don't advertise any tor addresses. In fact, the seed nodes don't advertise any listening addresses *at all* currently, but nodes are able to reconnect to them via the `lastAddress` field. It might be good to update the config files on the seed nodes to include their listening addresses - let me know if you agree.

I'm going to add some tests to ensure that listening addresses are advertised, saved, and used properly (we have some tests in place that do this but they're not comprehensive) and prevent connections to tor when we are not using tor.

I'm removing the bug & p1 labels for now, and I'll use this to track the enhancement of not connecting to tor when tor is disabled.

**Comment by kilrau** [comment] 2019-11-21 16:39
As discussed, what we do for now is adding 
```
  {
    nodePubKey: '02b66438730d1fcdf4a4ae5d3d73e847a272f160fee2938e132b52cab0a0d9cfc6',
    addresses: [{ host: 'xud1.simnet.exchangeunion.com', port: 28885 }],
  },
  {
    nodePubKey: '028599d05b18c0c3f8028915a17d603416f7276c822b6b2d20e71a3502bd0f9e0a',
    addresses: [{ host: 'xud2.simnet.exchangeunion.com', port: 28885 }],
  },
  {
    nodePubKey: '03fd337659e99e628d0487e4f87acf93e353db06f754dccc402f2de1b857a319d0',
    addresses: [{ host: 'xud3.simnet.exchangeunion.com', port: 28885 }],
  },
```
as advertised URIs each and restart by @sangaman

**Comment by sangaman** [comment] 2019-11-21 17:03
Config files on all 3 simnet nodes updated to include listening addresses.

**Comment by kilrau** [comment] 2019-11-21 17:13
Did you restart the nodes? I had simnet running while you were doing the changes, got disconnected from the 3 nodes and now I'm not getting re-connected.

https://paste.ubuntu.com/p/gY8mYsHPT9/

**Comment by kilrau** [comment] 2019-11-21 19:48
> I'm removing the bug & p1 labels for now, and I'll use this to track the enhancement of not connecting to tor when tor is disabled.

That's already done in https://github.com/ExchangeUnion/xud/issues/1154. So if you are of the opinion all is good now please close. My issue above remains though.

**Comment by kilrau** [comment] 2019-11-22 08:24
I kept my simnet running overnight. It failed to connect to some other  .onion peers all night (that's all it did):
```
xud_1     | 22/11/2019 07:41:26.910 [P2P] debug: Connection attempt #177 to 027becf1837c1776b3f1f0c7f1bc9402a76dff38c0b4b1e64eee118c5e8a05efec@al2nv6qcu22zpjesxrrmpgb7upd4snmk4lhanr3iywvq5n3nocvb5lid.onion:28885 failed: connect ECONNREFUSED 224.0.0.6:28885. retrying in 300 sec...
```
Then this morning it suddenly connected successfully to 2x .onion peers and xud1,2,3.simnet.exchangeunion.com: https://paste.ubuntu.com/p/wsjDrZsNvX/

**Comment by kilrau** [comment] 2019-11-22 14:15
`xud1.simnet.exchangeunion.com` was not connected. I just connected manually and it worked without issues. There is definitely a reconnection mystery of previously connected peers to be solved, but not sure if it's worth focusing on it now. You decide @sangaman

**Closed** 2019-12-05 16:38 UTC
