### ISSUE TITLE
Inbound peers block shutdown process

### ISSUE THREAD

**Issue by sangaman** [ExchangeUnion/xud#719] opened 2018-12-02 17:33 UTC
As identified in #699 by @offerm, we aren't closing pending inbound peer connections on shutdown. This can prevent `xud` from shutting down gracefully.

Edit: Per offer, it's not a pending connection that causes this issue but an established one. There must be something else coming into play because simply getting an inbound peer and shutting down doesn't reproduce the bug for me.

**Comment by sangaman** [comment] 2018-12-18 18:46
No, this one is still a mystery to me. I haven't been able to reproduce or deduce why it would happen.

**Comment by kilrau** [comment] 2019-01-02 16:36
Could you help reproduce? Moving to next milestone since not critical.

**Comment by kilrau** [comment] 2019-01-29 15:16
@moshababo experienced this one again with xud-simulation

**Comment by moshababo** [comment] 2019-02-02 18:36
@sangaman the issue is reproduced on `xud-simulation`. It still not ready to be run by others though, due to minor pending fix on `ltcd`. Will update here when it's ready.

**Comment by erkarl** [comment] 2019-04-15 07:52
It's possible that this issue is fixed in: https://github.com/ExchangeUnion/xud/pull/886 because it changes the shutdown logic a little to avoid incomplete shutdowns while connected to peers.

**Closed** 2019-04-16 07:36 UTC
Labels: bug, p2p
