### ISSUE TITLE
Newly installed xud can't connect to seed peers, manually connect to seed peer works immediately

### ISSUE THREAD

**Issue by reliveyy** [ExchangeUnion/xud#1862] opened 2020-09-02 09:46 UTC
I was running xud 1.0.0-rc.2-8531070d few hours ago. I got `AuthFailureInvalidTarget` and `WireProtocolErr` when xud try to connect to preset peers.

![image](https://user-images.githubusercontent.com/4723958/91965067-8b5d6680-ed42-11ea-8547-fe6d8edc1812.png)

After manually connect to the node below new peers came in (4 in total)

```
connect 03c7a8cdc3cf7203c1ba1ad5602622d551ae84a8e2aec5b6e50df73c287a6097f7@xud.kilrau.com:8885
```

Now I'm running xud 1.0.0-31bf1ff0. 5 peers shows up without manual intervention.

![image](https://user-images.githubusercontent.com/4723958/91966322-40dce980-ed44-11ea-8103-6d7444d7e91a.png)

**Comment by kilrau** [comment] 2020-09-02 17:20
I experienced similar behaviour before, let's add logs for every time we experience this.

**Comment by kilrau** [comment] 2020-09-02 17:34
Related: https://github.com/ExchangeUnion/xud/issues/1645

**Comment by kilrau** [comment] 2020-09-09 13:39
Likely related too: https://github.com/ExchangeUnion/xud/issues/1879

**Comment by kilrau** [comment] 2020-09-16 09:05
Related: https://github.com/ExchangeUnion/xud/issues/1699

**Comment by kilrau** [comment] 2020-09-25 10:43
Related: https://github.com/ExchangeUnion/xud/issues/1681

**Comment by kilrau** [comment] 2020-09-25 10:45
I have 3 simnet nodes, 2 with the same 3 common peers, 1 with 2 additional ones the other two don't have. Don't observe any connection attempt to connect to the two missing ones.

node 1:
```
simnet > listpeers

Peers:
┌───────────────────────────────────────────────────────────────────────┬───────────┬──────────────────────────────────────┐
│ Peer                                                                  │ Pairs     │ Details                              │
├───────────────────────────────────────────────────────────────────────┼───────────┼──────────────────────────────────────┤
│ Alias: OzoneYellow                                                    │ ETH/BTC   │ inbound: false                       │
│                                                                       │ LTC/BTC   │ version: 1.0.0                       │
│ Address ([node_key]@[host]:[port]):                                   │           │ time connected: 2939 seconds         │
│ 03ece33a30db1dbce4b62fa96a5e9541138a24997ef5672eebed2d332270e39542    │           │ BTC lnd key: 0252f36611...656161cbbf │
│ @xud1.simnet.exchangeunion.com:28885                                  │           │ LTC lnd key: 0252f36611...656161cbbf │
├───────────────────────────────────────────────────────────────────────┼───────────┼──────────────────────────────────────┤
│ Alias: SheriffSolution                                                │ ETH/BTC   │ inbound: false                       │
│                                                                       │ LTC/BTC   │ version: 1.0.1                       │
│ Address ([node_key]@[host]:[port]):                                   │ BTC/USDT  │ time connected: 2256 seconds         │
│ 03df4f36fa35bd242263e8d09d6b422108dab1f08d91237bb3aa2dad957cf08a71    │ LTC/USDT  │ BTC lnd key: 0217622759...17e6820d1f │
│ @xud.kilrau.com:28885                                                 │           │ LTC lnd key: 0217622759...17e6820d1f │
├───────────────────────────────────────────────────────────────────────┼───────────┼──────────────────────────────────────┤
│ Alias: HaveFame                                                       │ ETH/BTC   │ inbound: true                        │
│                                                                       │ LTC/BTC   │ version: 1.0.1                       │
│ Address ([node_key]@[host]:[port]):                                   │ LTC/USDT  │ time connected: 962 seconds          │
│ 0279726711d971ecb573ea77532a0b2e5d8a4357bc60a6589b2cc9cb1510b6ebcd    │ BTC/USDT  │ BTC lnd key: 03ca07d106...dad8d834b2 │
│ @127.0.0.1:60642                                                      │ BTC/DAI   │ LTC lnd key: 03ca07d106...dad8d834b2 │
│                                                                       │ USDT/DAI  │                                      │
├───────────────────────────────────────────────────────────────────────┼───────────┼──────────────────────────────────────┤
│ Alias: NeglectAcoustic                                                │ ETH/BTC   │ inbound: false                       │
│                                                                       │ LTC/BTC   │ version: 1.0.1                       │
│ Address ([node_key]@[host]:[port]):                                   │ LTC/USDT  │ time connected: 774 seconds          │
│ 03ad8a98151caa68e41412359b9b9c1e1467f1ed88b4bd3e70d8fad4ab795b3095    │ BTC/USDT  │ BTC lnd key: 035890310a...4ae3568c6c │
│ @mn5hbphgfbnzj2mfw6sppxkc2c57o7g77dgnwon32fc64dyhmd6vyoqd.onion:28885 │ HYDRO/BTC │ LTC lnd key: 035890310a...4ae3568c6c │
└───────────────────────────────────────────────────────────────────────┴───────────┴──────────────────────────────────────┘
```

node 2:
```
simnet > listpeers

Peers:
┌───────────────────────────────────────────────────────────────────────┬───────────┬──────────────────────────────────────┐
│ Peer                                                                  │ Pairs     │ Details                              │
├───────────────────────────────────────────────────────────────────────┼───────────┼──────────────────────────────────────┤
│ Alias: OzoneYellow                                                    │ ETH/BTC   │ inbound: false                       │
│                                                                       │ LTC/BTC   │ version: 1.0.0                       │
│ Address ([node_key]@[host]:[port]):                                   │           │ time connected: 951 seconds          │
│ 03ece33a30db1dbce4b62fa96a5e9541138a24997ef5672eebed2d332270e39542    │           │ BTC lnd key: 0252f36611...656161cbbf │
│ @xud1.simnet.exchangeunion.com:28885                                  │           │ LTC lnd key: 0252f36611...656161cbbf │
├───────────────────────────────────────────────────────────────────────┼───────────┼──────────────────────────────────────┤
│ Alias: SheriffSolution                                                │ ETH/BTC   │ inbound: false                       │
│                                                                       │ LTC/BTC   │ version: 1.0.1                       │
│ Address ([node_key]@[host]:[port]):                                   │ BTC/USDT  │ time connected: 951 seconds          │
│ 03df4f36fa35bd242263e8d09d6b422108dab1f08d91237bb3aa2dad957cf08a71    │ LTC/USDT  │ BTC lnd key: 0217622759...17e6820d1f │
│ @xud.kilrau.com:28885                                                 │           │ LTC lnd key: 0217622759...17e6820d1f │
├───────────────────────────────────────────────────────────────────────┼───────────┼──────────────────────────────────────┤
│ Alias: NestGrid                                                       │ ETH/BTC   │ inbound: false                       │
│                                                                       │ LTC/BTC   │ version: 1.0.1                       │
│ Address ([node_key]@[host]:[port]):                                   │ LTC/USDT  │ time connected: 949 seconds          │
│ 03cecb5ecd7f49902092cbf636b514ba3281aaf1bef95cfb249565ef65804c73f5    │ BTC/USDT  │ BTC lnd key: 0201f97524...f3cac460ae │
│ @irz7zesksmyhebod6nzkw6ogqktubuuo5kj77bwdkooxjooydrna4eyd.onion:28885 │ BTC/DAI   │ LTC lnd key: 0201f97524...f3cac460ae │
│                                                                       │ USDT/DAI  │                                      │
├───────────────────────────────────────────────────────────────────────┼───────────┼──────────────────────────────────────┤
│ Alias: NeglectAcoustic                                                │ ETH/BTC   │ inbound: false                       │
│                                                                       │ LTC/BTC   │ version: 1.0.1                       │
│ Address ([node_key]@[host]:[port]):                                   │ LTC/USDT  │ time connected: 934 seconds          │
│ 03ad8a98151caa68e41412359b9b9c1e1467f1ed88b4bd3e70d8fad4ab795b3095    │ BTC/USDT  │ BTC lnd key: 035890310a...4ae3568c6c │
│ @mn5hbphgfbnzj2mfw6sppxkc2c57o7g77dgnwon32fc64dyhmd6vyoqd.onion:28885 │ HYDRO/BTC │ LTC lnd key: 035890310a...4ae3568c6c │
└───────────────────────────────────────────────────────────────────────┴───────────┴──────────────────────────────────────┘
```

node 3:
```
simnet > listpeers

Peers:
┌───────────────────────────────────────────────────────────────────────┬───────────┬──────────────────────────────────────┐
│ Peer                                                                  │ Pairs     │ Details                              │
├───────────────────────────────────────────────────────────────────────┼───────────┼──────────────────────────────────────┤
│ Alias: ShortBlouse                                                    │ ETH/BTC   │ inbound: true                        │
│                                                                       │ LTC/BTC   │ version: 1.0.1                       │
│ Address ([node_key]@[host]:[port]):                                   │ LTC/USDT  │ time connected: 2253 seconds         │
│ 02562d5c0ae2916567ba9da4dab1c30d5adb180b4dba50b72d614b63f64902f434    │ BTC/USDT  │ BTC lnd key: 031ffe8409...9e53c31ce7 │
│ @194.34.132.57:16136                                                  │ BTC/DAI   │                                      │
│                                                                       │ USDT/DAI  │                                      │
├───────────────────────────────────────────────────────────────────────┼───────────┼──────────────────────────────────────┤
│ Alias: NestGrid                                                       │ ETH/BTC   │ inbound: true                        │
│                                                                       │ LTC/BTC   │ version: 1.0.1                       │
│ Address ([node_key]@[host]:[port]):                                   │ LTC/USDT  │ time connected: 2246 seconds         │
│ 03cecb5ecd7f49902092cbf636b514ba3281aaf1bef95cfb249565ef65804c73f5    │ BTC/USDT  │ BTC lnd key: 0201f97524...f3cac460ae │
│ @185.220.100.255:27262                                                │ BTC/DAI   │ LTC lnd key: 0201f97524...f3cac460ae │
│                                                                       │ USDT/DAI  │                                      │
├───────────────────────────────────────────────────────────────────────┼───────────┼──────────────────────────────────────┤
│ Alias: NeglectAcoustic                                                │ ETH/BTC   │ inbound: false                       │
│                                                                       │ LTC/BTC   │ version: 1.0.1                       │
│ Address ([node_key]@[host]:[port]):                                   │ LTC/USDT  │ time connected: 2139 seconds         │
│ 03ad8a98151caa68e41412359b9b9c1e1467f1ed88b4bd3e70d8fad4ab795b3095    │ BTC/USDT  │ BTC lnd key: 035890310a...4ae3568c6c │
│ @mn5hbphgfbnzj2mfw6sppxkc2c57o7g77dgnwon32fc64dyhmd6vyoqd.onion:28885 │ HYDRO/BTC │ LTC lnd key: 035890310a...4ae3568c6c │
├───────────────────────────────────────────────────────────────────────┼───────────┼──────────────────────────────────────┤
│ Alias: OzoneYellow                                                    │ ETH/BTC   │ inbound: false                       │
│                                                                       │ LTC/BTC   │ version: 1.0.0                       │
│ Address ([node_key]@[host]:[port]):                                   │           │ time connected: 2078 seconds         │
│ 03ece33a30db1dbce4b62fa96a5e9541138a24997ef5672eebed2d332270e39542    │           │ BTC lnd key: 0252f36611...656161cbbf │
│ @hsfkqybnlkql5fgm3h72mqnrl5rh543hulkp7j6tzs7thq3fznjrkcid.onion:28885 │           │ LTC lnd key: 0252f36611...656161cbbf │
├───────────────────────────────────────────────────────────────────────┼───────────┼──────────────────────────────────────┤
│ Alias: CattleImmune                                                   │ ETH/BTC   │ inbound: true                        │
│                                                                       │ LTC/BTC   │ version: 1.0.1                       │
│ Address ([node_key]@[host]:[port]):                                   │ LTC/USDT  │ time connected: 1552 seconds         │
│ 0344f4e933462bb56fbe869f22e9187d177a8d7bb7b451cc42a9fc3ceeef1fe1a6    │ BTC/USDT  │ BTC lnd key: 03332b1abe...e7980c6abb │
│ @95.10.2.98:4355                                                      │           │ LTC lnd key: 03332b1abe...e7980c6abb │
├───────────────────────────────────────────────────────────────────────┼───────────┼──────────────────────────────────────┤
│ Alias: HaveFame                                                       │ ETH/BTC   │ inbound: true                        │
│                                                                       │ LTC/BTC   │ version: 1.0.1                       │
│ Address ([node_key]@[host]:[port]):                                   │ LTC/USDT  │ time connected: 954 seconds          │
│ 0279726711d971ecb573ea77532a0b2e5d8a4357bc60a6589b2cc9cb1510b6ebcd    │ BTC/USDT  │ BTC lnd key: 03ca07d106...dad8d834b2 │
│ @185.220.100.240:4320                                                 │ BTC/DAI   │ LTC lnd key: 03ca07d106...dad8d834b2 │
│                                                                       │ USDT/DAI  │                                      │
└───────────────────────────────────────────────────────────────────────┴───────────┴──────────────────────────────────────┘
```

**Comment by rsercano** [comment] 2020-09-25 11:06
So in this case, I assume discovering doesn't work as desired @kilrau

**Comment by kilrau** [comment] 2020-09-25 11:18
Yep

**Comment by LePremierHomme** [comment] 2020-11-25 10:12
@reliveyy 
> I was running xud 1.0.0-rc.2-8531070d few hours ago. I got AuthFailureInvalidTarget and WireProtocolErr when xud try to connect to preset peers.

I don’t think that there’s a problem here.

Your connection to `xud.kilrau.com:8885` failed due to invalid pubkey,  and to `boltz.exchange:8885` due to an incompatible wire protocol (might be due to an incompatible xud version which wasn’t defined as such).
Later you manually connected to `xud.kilrau.com:8885` with the proper pubkey, and it succeeded. You probably got the 3 new peers from him. 
Later you upgraded your xud version, and your connection to `boltz.exchange:8885` succeeded as well.

**Comment by LePremierHomme** [comment] 2020-11-25 10:16
@peartobear 
> Same issue with running xud 1.0.0 was able to manually connect.

Your log is cut, please copy/paste it. Also, looks like your manual connects fail as well. 
So can't help with this yet - more info is needed.

**Comment by kilrau** [comment] 2020-11-25 10:34
Same here: no reliable way to reproduce this and I haven't seen this in a while. Closing until we found a way to reliably reproduce cc @raladev

**Closed by kilrau** 2020-11-25 10:34 UTC
Labels: P2, bug, p2p
